-- ----------------------------
-- Table structure for `ACCOUNTS`
-- ----------------------------
CREATE TABLE IF NOT EXISTS `ACCOUNTS` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `LAST_ACTIVATED_AT` DATETIME NOT NULL,
  `ACCESS_LEVEL` INT NOT NULL DEFAULT '0',
  `IP` VARCHAR(255) NOT NULL DEFAULT '',
  `HOST` VARCHAR(255) NOT NULL DEFAULT '',
  `IS_BANNED` BOOLEAN NOT NULL DEFAULT '0',
  `CHARACTER_SLOT` TINYINT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `ACCOUNTS`
-- ----------------------------
CREATE PRIMARY KEY IF NOT EXISTS `ACCOUNTS_PK` ON `ACCOUNTS`(`ID`);
CREATE UNIQUE INDEX IF NOT EXISTS `ACCOUNTS_UK` ON `ACCOUNTS`(`NAME`);
