-- ----------------------------
-- Table structure for `CHARACTER_BOOKMARKS`
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CHARACTER_BOOKMARKS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CHAR_ID` INT NOT NULL,
  `NAME` VARCHAR(255) DEFAULT NULL,
  `LOC_X` INT NOT NULL,
  `LOC_Y` INT NOT NULL,
  `MAP_ID` INT NOT NULL
);
-- ----------------------------
-- Index for `CHARACTER_BOOKMARKS`
-- ----------------------------
CREATE PRIMARY KEY IF NOT EXISTS `CHARACTER_BOOKMARKS_PK` ON `CHARACTER_BOOKMARKS`(`ID`);
CREATE INDEX IF NOT EXISTS `CHARACTER_BOOKMARKS_UK` ON `CHARACTER_BOOKMARKS`(`CHAR_ID`);
