-- ----------------------------
-- Table structure for `CHARACTER_SKILLS`
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CHARACTER_SKILLS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CHAR_ID` INT NOT NULL DEFAULT '0',
  `SKILL_ID` INT NOT NULL DEFAULT '0',
  `SKILL_NAME` VARCHAR(255) NOT NULL DEFAULT '',
  `IS_ACTIVE` TINYINT DEFAULT NULL,
  `ACTIVE_TIME_LEFT` INT DEFAULT NULL
);
-- ----------------------------
-- Index for `CHARACTER_SKILLS`
-- ----------------------------
CREATE PRIMARY KEY IF NOT EXISTS `CHARACTER_SKILLS_PK` ON `CHARACTER_SKILLS`(`ID`);
CREATE UNIQUE INDEX IF NOT EXISTS `CHARACTER_SKILLS_UK` ON `CHARACTER_SKILLS`(`CHAR_ID`,`SKILL_ID`);
