-- ----------------------------
-- Table structure for `CHAT_LOGS`
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CHAT_LOGS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` INT NOT NULL,
  `CHAR_ID` INT NOT NULL,
  `CLAN_ID` INT NOT NULL,
  `MAP_ID` INT NOT NULL,
  `LOC_X` INT NOT NULL,
  `LOC_Y` INT NOT NULL,
  `TYPE` INT NOT NULL,
  `TARGET_ACCOUNT_ID` INT DEFAULT NULL,
  `TARGET_CHAR_ID` INT DEFAULT NULL,
  `TARGET_CLAN_ID` INT DEFAULT NULL,
  `TARGET_MAP_ID` INT DEFAULT NULL,
  `TARGET_LOC_X` INT DEFAULT NULL,
  `TARGET_LOC_Y` INT DEFAULT NULL,
  `CONTENT` VARCHAR(255) NOT NULL,
  `DATETIME` DATETIME NOT NULL
);
-- ----------------------------
-- Index for `CHAT_LOGS`
-- ----------------------------
CREATE PRIMARY KEY IF NOT EXISTS `CHAT_LOGS_PK` ON `CHAT_LOGS`(`ID`);
