-- ----------------------------
-- Table structure for `HOUSE_AUCTION`
-- ----------------------------
CREATE TABLE IF NOT EXISTS `HOUSE_AUCTION` (
  `HOUSE_ID` INT NOT NULL DEFAULT '0',
  `HOUSE_NAME` VARCHAR(255) NOT NULL DEFAULT '',
  `HOUSE_AREA` INT NOT NULL DEFAULT '0',
  `DEADLINE` DATETIME DEFAULT NULL,
  `PRICE` INT NOT NULL DEFAULT '0',
  `LOCATION` VARCHAR(255) NOT NULL DEFAULT '',
  `OLD_OWNER` VARCHAR(255) NOT NULL DEFAULT '',
  `OLD_OWNER_ID` INT NOT NULL DEFAULT '0',
  `BIDDER` VARCHAR(255) NOT NULL DEFAULT '',
  `BIDDER_ID` INT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `HOUSE_AUCTION`
-- ----------------------------
CREATE PRIMARY KEY IF NOT EXISTS `HOUSE_AUCTION_PK` ON `HOUSE_AUCTION`(`HOUSE_ID`);
