-- ----------------------------
-- Table structure for `MAPIDS`
-- ----------------------------
DROP TABLE IF EXISTS `MAPIDS`;
CREATE TABLE `MAPIDS` (
  `MAP_ID` INT NOT NULL DEFAULT '0',
  `LOCATION_NAME` VARCHAR(255) DEFAULT NULL,
  `START_X` INT NOT NULL DEFAULT '0',
  `END_X` INT NOT NULL DEFAULT '0',
  `START_Y` INT NOT NULL DEFAULT '0',
  `END_Y` INT NOT NULL DEFAULT '0',
  `MONSTER_AMOUNT` INT NOT NULL DEFAULT '0',
  `DROP_RATE` FLOAT NOT NULL DEFAULT '0',
  `UNIQUE_RATE` FLOAT NOT NULL DEFAULT '1',
  `UNDERWATER` BOOLEAN NOT NULL DEFAULT '0',
  `MARKABLE` BOOLEAN NOT NULL DEFAULT '0',
  `TELEPORTABLE` BOOLEAN NOT NULL DEFAULT '0',
  `ESCAPABLE` BOOLEAN NOT NULL DEFAULT '0',
  `RESURRECTION` BOOLEAN NOT NULL DEFAULT '0',
  `PAINWAND` BOOLEAN NOT NULL DEFAULT '0',
  `PENALTY` BOOLEAN NOT NULL DEFAULT '0',
  `TAKE_PETS` BOOLEAN NOT NULL DEFAULT '0',
  `RECALL_PETS` BOOLEAN NOT NULL DEFAULT '0',
  `USABLE_ITEM` BOOLEAN NOT NULL DEFAULT '0',
  `USABLE_SKILL` BOOLEAN NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `MAPIDS`
-- ----------------------------
CREATE PRIMARY KEY `MAPIDS_PK` ON `MAPIDS`(`MAP_ID`);
