-- ----------------------------
-- Table structure for `mob_skills`
-- ----------------------------
DROP TABLE IF EXISTS `mob_skills`;
CREATE TABLE `mob_skills` (
  `MOB_ID` INT NOT NULL DEFAULT '0',
  `ACT_NO` INT NOT NULL DEFAULT '0',
  `MOB_NAME` VARCHAR(255) NOT NULL DEFAULT '',
  `TYPE` INT NOT NULL DEFAULT '0',
  `TRI_RND` INT NOT NULL DEFAULT '0',
  `TRI_HP` INT NOT NULL DEFAULT '0',
  `TRI_COMPANION_HP` INT NOT NULL DEFAULT '0',
  `TRI_RANGE` INT NOT NULL DEFAULT '0',
  `TRI_COUNT` INT NOT NULL DEFAULT '0',
  `CHANGE_TARGET` INT NOT NULL DEFAULT '0',
  `RANGE` INT NOT NULL DEFAULT '0',
  `AREA_WIDTH` INT NOT NULL DEFAULT '0',
  `AREA_HEIGHT` INT NOT NULL DEFAULT '0',
  `LEVERAGE` INT NOT NULL DEFAULT '0',
  `SKILL_ID` INT NOT NULL DEFAULT '0',
  `GFX_ID` INT NOT NULL DEFAULT '0',
  `ACT_ID` INT NOT NULL DEFAULT '0',
  `SUMMON_ID` INT NOT NULL DEFAULT '0',
  `SUMMON_MIN` INT NOT NULL DEFAULT '0',
  `SUMMON_MAX` INT NOT NULL DEFAULT '0',
  `POLY_ID` INT NOT NULL DEFAULT '0',
  `CHAT_ID` INT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `mob_skills`
-- ----------------------------
CREATE PRIMARY KEY `mob_skills_PK` ON `mob_skills`(`MOB_ID`,`ACT_NO`);
