-- ----------------------------
-- Table structure for `MOBSKILL`
-- ----------------------------
DROP TABLE IF EXISTS `MOBSKILL`;
CREATE TABLE `MOBSKILL` (
  `MOB_ID` INT NOT NULL DEFAULT '0',
  `ACT_NO` INT NOT NULL DEFAULT '0',
  `MOB_NAME` VARCHAR(255) NOT NULL DEFAULT '',
  `TYPE` INT NOT NULL DEFAULT '0',
  `TRI_RND` INT NOT NULL DEFAULT '0',
  `TRI_HP` INT NOT NULL DEFAULT '0',
  `TRI_COMPANION_HP` INT NOT NULL DEFAULT '0',
  `TRI_RANGE` INT NOT NULL DEFAULT '0',
  `TRI_COUNT` INT NOT NULL DEFAULT '0',
  `CHANGE_TARGET` INT NOT NULL DEFAULT '0',
  `RANGE` INT NOT NULL DEFAULT '0',
  `AREA_WIDTH` INT NOT NULL DEFAULT '0',
  `AREA_HEIGHT` INT NOT NULL DEFAULT '0',
  `LEVERAGE` INT NOT NULL DEFAULT '0',
  `SKILL_ID` INT NOT NULL DEFAULT '0',
  `GFXID` INT NOT NULL DEFAULT '0',
  `ACTID` INT NOT NULL DEFAULT '0',
  `SUMMON_ID` INT NOT NULL DEFAULT '0',
  `SUMMON_MIN` INT NOT NULL DEFAULT '0',
  `SUMMON_MAX` INT NOT NULL DEFAULT '0',
  `POLY_ID` INT NOT NULL DEFAULT '0',
  `CHAT_ID` INT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `MOBSKILL`
-- ----------------------------
CREATE PRIMARY KEY `MOBSKILL_PK` ON `MOBSKILL`(`MOB_ID`,`ACT_NO`);
