-- ----------------------------
-- Table structure for `NPCCHAT`
-- ----------------------------
DROP TABLE IF EXISTS `NPCCHAT`;
CREATE TABLE `NPCCHAT` (
  `NPC_ID` INT NOT NULL DEFAULT '0',
  `CHAT_TIMING` TINYINT NOT NULL DEFAULT '0',
  `NOTE` VARCHAR(255) NOT NULL DEFAULT '',
  `START_DELAY_TIME` INT NOT NULL DEFAULT '0',
  `CHAT_ID1` VARCHAR(255) NOT NULL DEFAULT '',
  `CHAT_ID2` VARCHAR(255) NOT NULL DEFAULT '',
  `CHAT_ID3` VARCHAR(255) NOT NULL DEFAULT '',
  `CHAT_ID4` VARCHAR(255) NOT NULL DEFAULT '',
  `CHAT_ID5` VARCHAR(255) NOT NULL DEFAULT '',
  `CHAT_INTERVAL` INT NOT NULL DEFAULT '0',
  `IS_SHOUT` BOOLEAN NOT NULL DEFAULT '0',
  `IS_WORLD_CHAT` BOOLEAN NOT NULL DEFAULT '0',
  `IS_REPEAT` BOOLEAN NOT NULL DEFAULT '0',
  `REPEAT_INTERVAL` INT NOT NULL DEFAULT '0',
  `GAME_TIME` INT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `NPCCHAT`
-- ----------------------------
CREATE PRIMARY KEY `NPCCHAT_PK` ON `NPCCHAT`(`NPC_ID`,`CHAT_TIMING`);
