-- ----------------------------
-- Table structure for `PET_ITEMS`
-- ----------------------------
DROP TABLE IF EXISTS `PET_ITEMS`;
CREATE TABLE `PET_ITEMS` (
  `ITEM_ID` INT NOT NULL,
  `HIT_MODIFIER` TINYINT NOT NULL DEFAULT '0',
  `DMG_MODIFIER` TINYINT NOT NULL DEFAULT '0',
  `AC` TINYINT NOT NULL DEFAULT '0',
  `STR` TINYINT NOT NULL DEFAULT '0',
  `CON` TINYINT NOT NULL DEFAULT '0',
  `DEX` TINYINT NOT NULL DEFAULT '0',
  `INT` TINYINT NOT NULL DEFAULT '0',
  `WIS` TINYINT NOT NULL DEFAULT '0',
  `HP` INT NOT NULL DEFAULT '0',
  `MP` INT NOT NULL DEFAULT '0',
  `SP` INT NOT NULL DEFAULT '0',
  `MR` TINYINT NOT NULL DEFAULT '0',
  `USE_TYPE` TINYINT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `PET_ITEMS`
-- ----------------------------
CREATE PRIMARY KEY `PET_ITEMS_PK` ON `PET_ITEMS`(`ITEM_ID`);
