-- ----------------------------
-- Table structure for `PET_TYPES`
-- ----------------------------
DROP TABLE IF EXISTS `PET_TYPES`;
CREATE TABLE `PET_TYPES` (
  `NPC_ID` INT NOT NULL,
  `TAME_ITEM_ID` INT NOT NULL DEFAULT '0',
  `MIN_HPUP` INT NOT NULL,
  `MAX_HPUP` INT NOT NULL,
  `MIN_MPUP` INT NOT NULL,
  `MAX_MPUP` INT NOT NULL,
  `TRANSFORM_ITEM_ID` INT NOT NULL DEFAULT '0',
  `TRANSFORM_NPC_ID` INT NOT NULL DEFAULT '0',
  `MESSAGE_ID1` INT NOT NULL,
  `MESSAGE_ID2` INT NOT NULL,
  `MESSAGE_ID3` INT NOT NULL,
  `MESSAGE_ID4` INT NOT NULL,
  `MESSAGE_ID5` INT NOT NULL,
  `DEFY_MESSAGE_ID` INT NOT NULL,
  `USE_EQUIPMENT` BOOLEAN NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `PET_TYPES`
-- ----------------------------
CREATE PRIMARY KEY `PET_TYPES_PK` ON `PET_TYPES`(`NPC_ID`);
