-- ----------------------------
-- Table structure for `PETITEM`
-- ----------------------------
DROP TABLE IF EXISTS `PETITEM`;
CREATE TABLE `PETITEM` (
  `ITEM_ID` INT NOT NULL,
  `NOTE` VARCHAR(255) NOT NULL DEFAULT '',
  `HIT_MODIFIER` TINYINT NOT NULL DEFAULT '0',
  `DMG_MODIFIER` TINYINT NOT NULL DEFAULT '0',
  `AC` TINYINT NOT NULL DEFAULT '0',
  `STR` TINYINT NOT NULL DEFAULT '0',
  `CON` TINYINT NOT NULL DEFAULT '0',
  `DEX` TINYINT NOT NULL DEFAULT '0',
  `INT` TINYINT NOT NULL DEFAULT '0',
  `WIS` TINYINT NOT NULL DEFAULT '0',
  `HP` INT NOT NULL DEFAULT '0',
  `MP` INT NOT NULL DEFAULT '0',
  `SP` INT NOT NULL DEFAULT '0',
  `MR` TINYINT NOT NULL DEFAULT '0',
  `USE_TYPE` TINYINT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `PETITEM`
-- ----------------------------
CREATE PRIMARY KEY `PETITEM_PK` ON `PETITEM`(`ITEM_ID`);
