-- ----------------------------
-- Table structure for `PETITEM`
-- ----------------------------
DROP TABLE IF EXISTS `PETITEM`;
CREATE TABLE `PETITEM` (
  `ITEM_ID` INT NOT NULL,
  `NOTE` VARCHAR(255) NOT NULL DEFAULT '',
  `HITMODIFIER` TINYINT NOT NULL DEFAULT '0',
  `DMGMODIFIER` TINYINT NOT NULL DEFAULT '0',
  `AC` TINYINT NOT NULL DEFAULT '0',
  `ADD_STR` TINYINT NOT NULL DEFAULT '0',
  `ADD_CON` TINYINT NOT NULL DEFAULT '0',
  `ADD_DEX` TINYINT NOT NULL DEFAULT '0',
  `ADD_INT` TINYINT NOT NULL DEFAULT '0',
  `ADD_WIS` TINYINT NOT NULL DEFAULT '0',
  `ADD_HP` INT NOT NULL DEFAULT '0',
  `ADD_MP` INT NOT NULL DEFAULT '0',
  `ADD_SP` INT NOT NULL DEFAULT '0',
  `M_DEF` TINYINT NOT NULL DEFAULT '0',
  `USE_TYPE` TINYINT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `PETITEM`
-- ----------------------------
CREATE PRIMARY KEY `PETITEM_PK` ON `PETITEM`(`ITEM_ID`);
