-- ----------------------------
-- Table structure for `RETURN_LOCATIONS`
-- ----------------------------
DROP TABLE IF EXISTS `RETURN_LOCATIONS`;
CREATE TABLE `RETURN_LOCATIONS` (
  `AREA_X1` INT NOT NULL DEFAULT '0',
  `AREA_Y1` INT NOT NULL DEFAULT '0',
  `AREA_X2` INT NOT NULL DEFAULT '0',
  `AREA_Y2` INT NOT NULL DEFAULT '0',
  `AREA_MAP_ID` INT NOT NULL DEFAULT '0',
  `GETBACK_X1` INT NOT NULL DEFAULT '0',
  `GETBACK_Y1` INT NOT NULL DEFAULT '0',
  `GETBACK_X2` INT NOT NULL DEFAULT '0',
  `GETBACK_Y2` INT NOT NULL DEFAULT '0',
  `GETBACK_X3` INT NOT NULL DEFAULT '0',
  `GETBACK_Y3` INT NOT NULL DEFAULT '0',
  `GETBACK_MAP_ID` INT NOT NULL DEFAULT '0',
  `GETBACK_TOWN_ID` TINYINT NOT NULL DEFAULT '0',
  `GETBACK_TOWN_ID_ELF` TINYINT NOT NULL DEFAULT '0',
  `GETBACK_TOWN_ID_DARKELF` TINYINT NOT NULL DEFAULT '0',
  `SCROLL_ESCAPE` BOOLEAN NOT NULL DEFAULT '1',
  `NOTE` VARCHAR(255) DEFAULT NULL
);
-- ----------------------------
-- Index for `RETURN_LOCATIONS`
-- ----------------------------
CREATE PRIMARY KEY `RETURN_LOCATIONS_PK` ON `RETURN_LOCATIONS`(`AREA_X1`,`AREA_Y1`,`AREA_X2`,`AREA_Y2`,`AREA_MAP_ID`);
