-- ----------------------------
-- Table structure for `SPAWNLIST_NPC`
-- ----------------------------
DROP TABLE IF EXISTS `SPAWNLIST_NPC`;
CREATE TABLE `SPAWNLIST_NPC` (
  `ID` INT NOT NULL,
  `LOCATION` varchar(255) NOT NULL DEFAULT '',
  `COUNT` INT NOT NULL DEFAULT '0',
  `NPC_TEMPLATEID` INT NOT NULL DEFAULT '0',
  `LOCX` INT NOT NULL DEFAULT '0',
  `LOCY` INT NOT NULL DEFAULT '0',
  `RANDOMX` INT NOT NULL DEFAULT '0',
  `RANDOMY` INT NOT NULL DEFAULT '0',
  `HEADING` INT NOT NULL DEFAULT '0' COMMENT '↑1 ↗2→3↘4↓5 ↙6←7↖0',
  `RESPAWN_DELAY` INT NOT NULL DEFAULT '0',
  `MAPID` INT NOT NULL DEFAULT '0',
  `MOVEMENT_DISTANCE` INT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `SPAWNLIST_NPC`
-- ----------------------------
CREATE PRIMARY KEY `SPAWNLIST_NPC_PK` ON `SPAWNLIST_NPC`(`ID`);
