-- ----------------------------
-- Table structure for `SPAWNLIST`
-- ----------------------------
DROP TABLE IF EXISTS `SPAWNLIST`;
CREATE TABLE `SPAWNLIST` (
  `ID` INT NOT NULL,
  `LOCATION` VARCHAR(255) NOT NULL DEFAULT '',
  `COUNT` INT NOT NULL DEFAULT '0',
  `NPC_TEMPLATE_ID` INT NOT NULL DEFAULT '0',
  `GROUP_ID` INT NOT NULL DEFAULT '0',
  `LOC_X` INT NOT NULL DEFAULT '0',
  `LOC_Y` INT NOT NULL DEFAULT '0',
  `RANDOM_X` INT NOT NULL DEFAULT '0',
  `RANDOM_Y` INT NOT NULL DEFAULT '0',
  `LOC_X1` INT NOT NULL DEFAULT '0',
  `LOC_Y1` INT NOT NULL DEFAULT '0',
  `LOC_X2` INT NOT NULL DEFAULT '0',
  `LOC_Y2` INT NOT NULL DEFAULT '0',
  `HEADING` INT NOT NULL DEFAULT '0',
  `MIN_RESPAWN_DELAY` INT NOT NULL DEFAULT '0',
  `MAX_RESPAWN_DELAY` INT NOT NULL DEFAULT '0',
  `MAP_ID` INT NOT NULL DEFAULT '0',
  `RESPAWN_SCREEN` BOOLEAN NOT NULL DEFAULT '0',
  `MOVEMENT_DISTANCE` INT NOT NULL DEFAULT '0',
  `REST` BOOLEAN NOT NULL DEFAULT '0',
  `NEAR_SPAWN` BOOLEAN NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `SPAWNLIST`
-- ----------------------------
CREATE PRIMARY KEY `SPAWNLIST_PK` ON `SPAWNLIST`(`ID`);
