-- ----------------------------
-- Table structure for `SPAWN_BOSS_MOBS`
-- ----------------------------
DROP TABLE IF EXISTS `SPAWN_BOSS_MOBS`;
CREATE TABLE `SPAWN_BOSS_MOBS` (
  `ID` INT NOT NULL,
  `CYCLE_TYPE` VARCHAR(255) DEFAULT NULL,
  `COUNT` INT NOT NULL DEFAULT '0',
  `NPC_ID` INT NOT NULL,
  `GROUP_ID` INT NOT NULL DEFAULT '0',
  `LOC_X` INT NOT NULL DEFAULT '0',
  `LOC_Y` INT NOT NULL DEFAULT '0',
  `RANDOM_X` INT NOT NULL DEFAULT '0',
  `RANDOM_Y` INT NOT NULL DEFAULT '0',
  `LOC_X1` INT NOT NULL DEFAULT '0',
  `LOC_Y1` INT NOT NULL DEFAULT '0',
  `LOC_X2` INT NOT NULL DEFAULT '0',
  `LOC_Y2` INT NOT NULL DEFAULT '0',
  `HEADING` INT NOT NULL DEFAULT '0',
  `MAP_ID` INT NOT NULL DEFAULT '0',
  `RESPAWN_SCREEN` BOOLEAN NOT NULL DEFAULT '0',
  `MOVEMENT_DISTANCE` INT NOT NULL DEFAULT '0',
  `REST` BOOLEAN NOT NULL DEFAULT '0',
  `SPAWN_TYPE` TINYINT NOT NULL DEFAULT '0',
  `PERCENTAGE` TINYINT NOT NULL DEFAULT '100'
);
-- ----------------------------
-- Index for `SPAWN_BOSS_MOBS`
-- ----------------------------
CREATE PRIMARY KEY `SPAWN_BOSS_MOBS_PK` ON `SPAWN_BOSS_MOBS`(`ID`);
