-- ----------------------------
-- Table structure for `SPAWNLIST`
-- ----------------------------
DROP TABLE IF EXISTS `SPAWNLIST`;
CREATE TABLE `SPAWNLIST` (
  `ID` INT NOT NULL,
  `LOCATION` VARCHAR(255) NOT NULL DEFAULT '',
  `COUNT` INT NOT NULL DEFAULT '0',
  `NPC_TEMPLATEID` INT NOT NULL DEFAULT '0',
  `GROUP_ID` INT NOT NULL DEFAULT '0',
  `LOCX` INT NOT NULL DEFAULT '0',
  `LOCY` INT NOT NULL DEFAULT '0',
  `RANDOMX` INT NOT NULL DEFAULT '0',
  `RANDOMY` INT NOT NULL DEFAULT '0',
  `LOCX1` INT NOT NULL DEFAULT '0',
  `LOCY1` INT NOT NULL DEFAULT '0',
  `LOCX2` INT NOT NULL DEFAULT '0',
  `LOCY2` INT NOT NULL DEFAULT '0',
  `HEADING` INT NOT NULL DEFAULT '0',
  `MIN_RESPAWN_DELAY` INT NOT NULL DEFAULT '0',
  `MAX_RESPAWN_DELAY` INT NOT NULL DEFAULT '0',
  `MAPID` INT NOT NULL DEFAULT '0',
  `RESPAWN_SCREEN` BOOLEAN NOT NULL DEFAULT '0',
  `MOVEMENT_DISTANCE` INT NOT NULL DEFAULT '0',
  `REST` BOOLEAN NOT NULL DEFAULT '0',
  `NEAR_SPAWN` BOOLEAN NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `SPAWNLIST`
-- ----------------------------
CREATE PRIMARY KEY `SPAWNLIST_PK` ON `SPAWNLIST`(`ID`);
