-- ----------------------------
-- Table structure for `TOWN`
-- ----------------------------
DROP TABLE IF EXISTS `TOWN`;
CREATE TABLE `TOWN` (
  `TOWN_ID` INT NOT NULL DEFAULT '0',
  `NAME` VARCHAR(255) NOT NULL DEFAULT '',
  `LEADER_ID` INT NOT NULL DEFAULT '0',
  `LEADER_NAME` VARCHAR(255) DEFAULT NULL,
  `TAX_RATE` INT NOT NULL DEFAULT '0',
  `TAX_RATE_RESERVED` INT NOT NULL DEFAULT '0',
  `SALES_MONEY` INT NOT NULL DEFAULT '0',
  `SALES_MONEY_YESTERDAY` INT NOT NULL DEFAULT '0',
  `TOWN_TAX` INT NOT NULL DEFAULT '0',
  `TOWN_FIX_TAX` INT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `TOWN`
-- ----------------------------
CREATE PRIMARY KEY `TOWN_PK` ON `TOWN`(`TOWN_ID`);
