-- ----------------------------
-- Table structure for `TRAPS`
-- ----------------------------
DROP TABLE IF EXISTS `TRAPS`;
CREATE TABLE `TRAPS` (
  `ID` INT NOT NULL,
  `NOTE` VARCHAR(255) DEFAULT NULL,
  `TYPE` VARCHAR(255) NOT NULL,
  `GFX_ID` INT NOT NULL DEFAULT '0',
  `IS_DETECTIONABLE` BOOLEAN NOT NULL DEFAULT '0',
  `BASE` INT NOT NULL DEFAULT '0',
  `DICE` INT NOT NULL DEFAULT '0',
  `DICE_COUNT` INT NOT NULL DEFAULT '0',
  `POISON_TYPE` VARCHAR(1) NOT NULL DEFAULT 'n',
  `POISON_DELAY` INT NOT NULL DEFAULT '0',
  `POISON_TIME` INT NOT NULL DEFAULT '0',
  `POISON_DAMAGE` INT NOT NULL DEFAULT '0',
  `MONSTER_NPC_ID` INT NOT NULL DEFAULT '0',
  `MONSTER_COUNT` INT NOT NULL DEFAULT '0',
  `TELEPORT_X` INT NOT NULL DEFAULT '0',
  `TELEPORT_Y` INT NOT NULL DEFAULT '0',
  `TELEPORT_MAP_ID` INT NOT NULL DEFAULT '0',
  `SKILL_ID` INT NOT NULL DEFAULT '0',
  `SKILL_TIME_SECONDS` INT NOT NULL DEFAULT '0',
  `SWITCH_ID` INT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `TRAPS`
-- ----------------------------
CREATE PRIMARY KEY `TRAPS_PK` ON `TRAPS`(`ID`);
