-- ----------------------------
-- Table structure for `UBS`
-- ----------------------------
DROP TABLE IF EXISTS `UBS`;
CREATE TABLE `UBS` (
  `ID` INT NOT NULL DEFAULT '0',
  `NAME` VARCHAR(255) NOT NULL DEFAULT '',
  `MAP_ID` INT NOT NULL DEFAULT '0',
  `AREA_X1` INT NOT NULL DEFAULT '0',
  `AREA_Y1` INT NOT NULL DEFAULT '0',
  `AREA_X2` INT NOT NULL DEFAULT '0',
  `AREA_Y2` INT NOT NULL DEFAULT '0',
  `MIN_LEVEL` INT NOT NULL DEFAULT '0',
  `MAX_LEVEL` INT NOT NULL DEFAULT '0',
  `MAX_PLAYER` INT NOT NULL DEFAULT '0',
  `ENTER_ROYAL` TINYINT NOT NULL DEFAULT '0',
  `ENTER_KNIGHT` TINYINT NOT NULL DEFAULT '0',
  `ENTER_WIZARD` TINYINT NOT NULL DEFAULT '0',
  `ENTER_ELF` TINYINT NOT NULL DEFAULT '0',
  `ENTER_DARKELF` TINYINT NOT NULL DEFAULT '0',
  `ENTER_DRAGONKNIGHT` TINYINT NOT NULL DEFAULT '0',
  `ENTER_ILLUSIONIST` TINYINT NOT NULL DEFAULT '0',
  `ENTER_MALE` TINYINT NOT NULL DEFAULT '0',
  `ENTER_FEMALE` TINYINT NOT NULL DEFAULT '0',
  `USE_POT` TINYINT NOT NULL DEFAULT '0',
  `HPR_BONUS` INT NOT NULL DEFAULT '0',
  `MPR_BONUS` INT NOT NULL DEFAULT '0'
);
-- ----------------------------
-- Index for `UBS`
-- ----------------------------
CREATE PRIMARY KEY `UBS_PK` ON `UBS`(`ID`);
