#!/bin/bash
driver='mysql'
locale='ja'
cat ./schema/$driver/accounts.sql > create_tables.sql
cat ./schema/$driver/armors.sql >> create_tables.sql
cat ./schema/$driver/armor_sets.sql >> create_tables.sql
cat ./schema/$driver/ban_ips.sql >> create_tables.sql
cat ./schema/$driver/beginner_items.sql >> create_tables.sql
cat ./schema/$driver/board.sql >> create_tables.sql
cat ./schema/$driver/house_auction.sql >> create_tables.sql
cat ./schema/$driver/castles.sql >> create_tables.sql
cat ./schema/$driver/character_buddys.sql >> create_tables.sql
cat ./schema/$driver/character_buffs.sql >> create_tables.sql
cat ./schema/$driver/character_configs.sql >> create_tables.sql
cat ./schema/$driver/character_quests.sql >> create_tables.sql
cat ./schema/$driver/character_skills.sql >> create_tables.sql
cat ./schema/$driver/character_bookmarks.sql >> create_tables.sql
cat ./schema/$driver/characters.sql >> create_tables.sql
cat ./schema/$driver/clans.sql >> create_tables.sql
cat ./schema/$driver/commands.sql >> create_tables.sql
cat ./schema/$driver/cooking_ingredients.sql >> create_tables.sql
cat ./schema/$driver/cooking_recipes.sql >> create_tables.sql
cat ./schema/$driver/door_gfxs.sql >> create_tables.sql
cat ./schema/$driver/drop_rates.sql >> create_tables.sql
cat ./schema/$driver/drop_items.sql >> create_tables.sql
cat ./schema/$driver/dungeons.sql >> create_tables.sql
cat ./schema/$driver/dungeon_random.sql >> create_tables.sql
cat ./schema/$driver/etc_items.sql >> create_tables.sql
cat ./schema/$driver/return_locations.sql >> create_tables.sql
cat ./schema/$driver/restart_locations.sql >> create_tables.sql
cat ./schema/$driver/houses.sql >> create_tables.sql
cat ./schema/$driver/inns.sql >> create_tables.sql
cat ./schema/$driver/inn_keys.sql >> create_tables.sql
cat ./schema/$driver/inventory_items.sql >> create_tables.sql
cat ./schema/$driver/letters.sql >> create_tables.sql
cat ./schema/$driver/log_accelerator.sql >> create_tables.sql
cat ./schema/$driver/log_chat.sql >> create_tables.sql
cat ./schema/$driver/log_enchant.sql >> create_tables.sql
cat ./schema/$driver/magic_dolls.sql >> create_tables.sql
cat ./schema/$driver/mails.sql >> create_tables.sql
cat ./schema/$driver/map_ids.sql >> create_tables.sql
cat ./schema/$driver/map_timers.sql >> create_tables.sql
cat ./schema/$driver/mob_groups.sql >> create_tables.sql
cat ./schema/$driver/mob_skills.sql >> create_tables.sql
cat ./schema/$driver/npc.sql >> create_tables.sql
cat ./schema/$driver/npc_actions.sql >> create_tables.sql
cat ./schema/$driver/npc_chats.sql >> create_tables.sql
cat ./schema/$driver/pet_items.sql >> create_tables.sql
cat ./schema/$driver/pets.sql >> create_tables.sql
cat ./schema/$driver/pet_types.sql >> create_tables.sql
cat ./schema/$driver/polymorphs.sql >> create_tables.sql
cat ./schema/$driver/race_tickets.sql >> create_tables.sql
cat ./schema/$driver/resolvents.sql >> create_tables.sql
cat ./schema/$driver/shops.sql >> create_tables.sql
cat ./schema/$driver/skills.sql >> create_tables.sql
cat ./schema/$driver/spawn_mobs.sql >> create_tables.sql
cat ./schema/$driver/spawn_boss.sql >> create_tables.sql
cat ./schema/$driver/spawn_doors.sql >> create_tables.sql
cat ./schema/$driver/spawn_furnitures.sql >> create_tables.sql
cat ./schema/$driver/spawn_lights.sql >> create_tables.sql
cat ./schema/$driver/spawn_npc.sql >> create_tables.sql
cat ./schema/$driver/spawn_times.sql >> create_tables.sql
cat ./schema/$driver/spawn_traps.sql >> create_tables.sql
cat ./schema/$driver/spawn_ub.sql >> create_tables.sql
cat ./schema/$driver/spr_actions.sql >> create_tables.sql
cat ./schema/$driver/towns.sql >> create_tables.sql
cat ./schema/$driver/traps.sql >> create_tables.sql
cat ./schema/$driver/ub_managers.sql >> create_tables.sql
cat ./schema/$driver/ub_settings.sql >> create_tables.sql
cat ./schema/$driver/ub_times.sql >> create_tables.sql
cat ./schema/$driver/weapons.sql >> create_tables.sql
cat ./schema/$driver/weapon_skills.sql >> create_tables.sql
cat ./records/$locale/armors.sql >> create_tables.sql
cat ./records/$locale/armor_sets.sql >> create_tables.sql
cat ./records/$locale/beginner_items.sql >> create_tables.sql
cat ./records/$locale/house_auction.sql >> create_tables.sql
cat ./records/$locale/castles.sql >> create_tables.sql
cat ./records/$locale/commands.sql >> create_tables.sql
cat ./records/$locale/cooking_ingredients.sql >> create_tables.sql
cat ./records/$locale/cooking_recipes.sql >> create_tables.sql
cat ./records/$locale/door_gfxs.sql >> create_tables.sql
cat ./records/$locale/drop_rates.sql >> create_tables.sql
cat ./records/$locale/drop_items.sql >> create_tables.sql
cat ./records/$locale/dungeons.sql >> create_tables.sql
cat ./records/$locale/dungeon_random.sql >> create_tables.sql
cat ./records/$locale/etc_items.sql >> create_tables.sql
cat ./records/$locale/return_locations.sql >> create_tables.sql
cat ./records/$locale/restart_locations.sql >> create_tables.sql
cat ./records/$locale/houses.sql >> create_tables.sql
cat ./records/$locale/inns.sql >> create_tables.sql
cat ./records/$locale/magic_dolls.sql >> create_tables.sql
cat ./records/$locale/map_ids.sql >> create_tables.sql
cat ./records/$locale/mob_groups.sql >> create_tables.sql
cat ./records/$locale/mob_skills.sql >> create_tables.sql
cat ./records/$locale/npc.sql >> create_tables.sql
cat ./records/$locale/npc_actions.sql >> create_tables.sql
cat ./records/$locale/npc_chats.sql >> create_tables.sql
cat ./records/$locale/pet_items.sql >> create_tables.sql
cat ./records/$locale/pet_types.sql >> create_tables.sql
cat ./records/$locale/polymorphs.sql >> create_tables.sql
cat ./records/$locale/resolvents.sql >> create_tables.sql
cat ./records/$locale/shops.sql >> create_tables.sql
cat ./records/$locale/skills.sql >> create_tables.sql
cat ./records/$locale/spawn_mobs.sql >> create_tables.sql
cat ./records/$locale/spawn_boss.sql >> create_tables.sql
cat ./records/$locale/spawn_doors.sql >> create_tables.sql
cat ./records/$locale/spawn_lights.sql >> create_tables.sql
cat ./records/$locale/spawn_npc.sql >> create_tables.sql
cat ./records/$locale/spawn_times.sql >> create_tables.sql
cat ./records/$locale/spawn_traps.sql >> create_tables.sql
cat ./records/$locale/spawn_ub.sql >> create_tables.sql
cat ./records/$locale/spr_actions.sql >> create_tables.sql
cat ./records/$locale/towns.sql >> create_tables.sql
cat ./records/$locale/traps.sql >> create_tables.sql
cat ./records/$locale/ub_managers.sql >> create_tables.sql
cat ./records/$locale/ub_settings.sql >> create_tables.sql
cat ./records/$locale/ub_times.sql >> create_tables.sql
cat ./records/$locale/weapons.sql >> create_tables.sql
cat ./records/$locale/weapon_skills.sql >> create_tables.sql
