type .\english\armor.sql > update_tables.sql
type .\english\armor_set.sql >> update_tables.sql
type .\english\beginner_items.sql >> update_tables.sql
type .\english\commands.sql >> update_tables.sql
type .\english\cooking_ingredients.sql >> update_tables.sql
type .\english\cooking_recipes.sql >> update_tables.sql
type .\english\door_gfxs.sql >> update_tables.sql
type .\english\drop_item.sql >> update_tables.sql
type .\english\droplist.sql >> update_tables.sql
type .\english\dungeon.sql >> update_tables.sql
type .\english\dungeon_random.sql >> update_tables.sql
type .\english\etcitem.sql >> update_tables.sql
type .\english\getback.sql >> update_tables.sql
type .\english\getback_restart.sql >> update_tables.sql
type .\english\magic_doll.sql >> update_tables.sql
type .\english\mapids.sql >> update_tables.sql
type .\english\mobgroup.sql >> update_tables.sql
type .\english\mobskill.sql >> update_tables.sql
type .\english\npc.sql >> update_tables.sql
type .\english\npcaction.sql >> update_tables.sql
type .\english\npcchat.sql >> update_tables.sql
type .\english\petitem.sql >> update_tables.sql
type .\english\pettypes.sql >> update_tables.sql
type .\english\polymorphs.sql >> update_tables.sql
type .\english\resolvent.sql >> update_tables.sql
type .\english\shop.sql >> update_tables.sql
type .\english\skills.sql >> update_tables.sql
type .\english\spawnlist.sql >> update_tables.sql
type .\english\spawnlist_boss.sql >> update_tables.sql
type .\english\spawnlist_door.sql >> update_tables.sql
type .\english\spawnlist_furniture.sql >> update_tables.sql
type .\english\spawnlist_light.sql >> update_tables.sql
type .\english\spawnlist_npc.sql >> update_tables.sql
type .\english\spawnlist_time.sql >> update_tables.sql
type .\english\spawnlist_trap.sql >> update_tables.sql
type .\english\spawnlist_ub.sql >> update_tables.sql
type .\english\spr_action.sql >> update_tables.sql
type .\english\trap.sql >> update_tables.sql
type .\english\ub_managers.sql >> update_tables.sql
type .\english\ub_settings.sql >> update_tables.sql
type .\english\ub_times.sql >> update_tables.sql
type .\english\weapon.sql >> update_tables.sql
type .\english\weapon_skill.sql >> update_tables.sql
