type .\taiwanese\accounts.sql > create_tables.sql
type .\taiwanese\armor.sql >> create_tables.sql
type .\taiwanese\armor_set.sql >> create_tables.sql
type .\taiwanese\ban_ip.sql >> create_tables.sql
type .\taiwanese\beginner_items.sql >> create_tables.sql
type .\taiwanese\board.sql >> create_tables.sql
type .\taiwanese\board_auction.sql >> create_tables.sql
type .\taiwanese\castle.sql >> create_tables.sql
type .\taiwanese\character_buddys.sql >> create_tables.sql
type .\taiwanese\character_buffs.sql >> create_tables.sql
type .\taiwanese\character_config.sql >> create_tables.sql
type .\taiwanese\character_quests.sql >> create_tables.sql
type .\taiwanese\character_skills.sql >> create_tables.sql
type .\taiwanese\character_teleport.sql >> create_tables.sql
type .\taiwanese\characters.sql >> create_tables.sql
type .\taiwanese\clan_data.sql >> create_tables.sql
type .\taiwanese\commands.sql >> create_tables.sql
type .\taiwanese\cooking_ingredients.sql >> create_tables.sql
type .\taiwanese\cooking_recipes.sql >> create_tables.sql
type .\taiwanese\door_gfxs.sql >> create_tables.sql
type .\taiwanese\drop_item.sql >> create_tables.sql
type .\taiwanese\droplist.sql >> create_tables.sql
type .\taiwanese\dungeon.sql >> create_tables.sql
type .\taiwanese\dungeon_random.sql >> create_tables.sql
type .\taiwanese\etcitem.sql >> create_tables.sql
type .\taiwanese\getback.sql >> create_tables.sql
type .\taiwanese\getback_restart.sql >> create_tables.sql
type .\taiwanese\house.sql >> create_tables.sql
type .\taiwanese\inn.sql >> create_tables.sql
type .\taiwanese\inn_key.sql >> create_tables.sql
type .\taiwanese\inventory_items.sql >> create_tables.sql
type .\taiwanese\letter.sql >> create_tables.sql
type .\taiwanese\log_accelerator.sql >> create_tables.sql
type .\taiwanese\log_chat.sql >> create_tables.sql
type .\taiwanese\log_enchant.sql >> create_tables.sql
type .\taiwanese\magic_doll.sql >> create_tables.sql
type .\taiwanese\mail.sql >> create_tables.sql
type .\taiwanese\mapids.sql >> create_tables.sql
type .\taiwanese\map_timer.sql >> create_tables.sql
type .\taiwanese\mobgroup.sql >> create_tables.sql
type .\taiwanese\mobskill.sql >> create_tables.sql
type .\taiwanese\npc.sql >> create_tables.sql
type .\taiwanese\npcaction.sql >> create_tables.sql
type .\taiwanese\npcchat.sql >> create_tables.sql
type .\taiwanese\petitem.sql >> create_tables.sql
type .\taiwanese\pets.sql >> create_tables.sql
type .\taiwanese\pettypes.sql >> create_tables.sql
type .\taiwanese\polymorphs.sql >> create_tables.sql
type .\taiwanese\race_ticket.sql >> create_tables.sql
type .\taiwanese\resolvent.sql >> create_tables.sql
type .\taiwanese\shop.sql >> create_tables.sql
type .\taiwanese\skills.sql >> create_tables.sql
type .\taiwanese\spawnlist.sql >> create_tables.sql
type .\taiwanese\spawnlist_boss.sql >> create_tables.sql
type .\taiwanese\spawnlist_door.sql >> create_tables.sql
type .\taiwanese\spawnlist_furniture.sql >> create_tables.sql
type .\taiwanese\spawnlist_light.sql >> create_tables.sql
type .\taiwanese\spawnlist_npc.sql >> create_tables.sql
type .\taiwanese\spawnlist_time.sql >> create_tables.sql
type .\taiwanese\spawnlist_trap.sql >> create_tables.sql
type .\taiwanese\spawnlist_ub.sql >> create_tables.sql
type .\taiwanese\spr_action.sql >> create_tables.sql
type .\taiwanese\town.sql >> create_tables.sql
type .\taiwanese\trap.sql >> create_tables.sql
type .\taiwanese\ub_managers.sql >> create_tables.sql
type .\taiwanese\ub_settings.sql >> create_tables.sql
type .\taiwanese\ub_times.sql >> create_tables.sql
type .\taiwanese\weapon.sql >> create_tables.sql
type .\taiwanese\weapon_skill.sql >> create_tables.sql
