#!/bin/bash
driver='mysql'
locale='ja'
cat ./schema/$driver/armor.sql > update_tables.sql
cat ./schema/$driver/armor_set.sql >> update_tables.sql
cat ./schema/$driver/beginner_items.sql >> update_tables.sql
cat ./schema/$driver/commands.sql >> update_tables.sql
cat ./schema/$driver/cooking_ingredients.sql >> update_tables.sql
cat ./schema/$driver/cooking_recipes.sql >> update_tables.sql
cat ./schema/$driver/door_gfxs.sql >> update_tables.sql
cat ./schema/$driver/drop_item.sql >> update_tables.sql
cat ./schema/$driver/droplist.sql >> update_tables.sql
cat ./schema/$driver/dungeon.sql >> update_tables.sql
cat ./schema/$driver/dungeon_random.sql >> update_tables.sql
cat ./schema/$driver/etcitem.sql >> update_tables.sql
cat ./schema/$driver/getback.sql >> update_tables.sql
cat ./schema/$driver/getback_restart.sql >> update_tables.sql
cat ./schema/$driver/magic_doll.sql >> update_tables.sql
cat ./schema/$driver/mapids.sql >> update_tables.sql
cat ./schema/$driver/mobgroup.sql >> update_tables.sql
cat ./schema/$driver/mobskill.sql >> update_tables.sql
cat ./schema/$driver/npc.sql >> update_tables.sql
cat ./schema/$driver/npcaction.sql >> update_tables.sql
cat ./schema/$driver/npcchat.sql >> update_tables.sql
cat ./schema/$driver/petitem.sql >> update_tables.sql
cat ./schema/$driver/pettypes.sql >> update_tables.sql
cat ./schema/$driver/polymorphs.sql >> update_tables.sql
cat ./schema/$driver/resolvent.sql >> update_tables.sql
cat ./schema/$driver/shop.sql >> update_tables.sql
cat ./schema/$driver/skills.sql >> update_tables.sql
cat ./schema/$driver/spawnlist.sql >> update_tables.sql
cat ./schema/$driver/spawnlist_boss.sql >> update_tables.sql
cat ./schema/$driver/spawnlist_door.sql >> update_tables.sql
cat ./schema/$driver/spawnlist_light.sql >> update_tables.sql
cat ./schema/$driver/spawnlist_npc.sql >> update_tables.sql
cat ./schema/$driver/spawnlist_time.sql >> update_tables.sql
cat ./schema/$driver/spawnlist_trap.sql >> update_tables.sql
cat ./schema/$driver/spawnlist_ub.sql >> update_tables.sql
cat ./schema/$driver/spr_action.sql >> update_tables.sql
cat ./schema/$driver/trap.sql >> update_tables.sql
cat ./schema/$driver/ub_managers.sql >> update_tables.sql
cat ./schema/$driver/ub_settings.sql >> update_tables.sql
cat ./schema/$driver/ub_times.sql >> update_tables.sql
cat ./schema/$driver/weapon.sql >> update_tables.sql
cat ./schema/$driver/weapon_skill.sql >> update_tables.sql
cat ./records/$locale/armor.sql >> update_tables.sql
cat ./records/$locale/armor_set.sql >> update_tables.sql
cat ./records/$locale/beginner_items.sql >> update_tables.sql
cat ./records/$locale/commands.sql >> update_tables.sql
cat ./records/$locale/cooking_ingredients.sql >> update_tables.sql
cat ./records/$locale/cooking_recipes.sql >> update_tables.sql
cat ./records/$locale/door_gfxs.sql >> update_tables.sql
cat ./records/$locale/drop_item.sql >> update_tables.sql
cat ./records/$locale/droplist.sql >> update_tables.sql
cat ./records/$locale/dungeon.sql >> update_tables.sql
cat ./records/$locale/dungeon_random.sql >> update_tables.sql
cat ./records/$locale/etcitem.sql >> update_tables.sql
cat ./records/$locale/getback.sql >> update_tables.sql
cat ./records/$locale/getback_restart.sql >> update_tables.sql
cat ./records/$locale/magic_doll.sql >> update_tables.sql
cat ./records/$locale/mapids.sql >> update_tables.sql
cat ./records/$locale/mobgroup.sql >> update_tables.sql
cat ./records/$locale/mobskill.sql >> update_tables.sql
cat ./records/$locale/npc.sql >> update_tables.sql
cat ./records/$locale/npcaction.sql >> update_tables.sql
cat ./records/$locale/npcchat.sql >> update_tables.sql
cat ./records/$locale/petitem.sql >> update_tables.sql
cat ./records/$locale/pettypes.sql >> update_tables.sql
cat ./records/$locale/polymorphs.sql >> update_tables.sql
cat ./records/$locale/resolvent.sql >> update_tables.sql
cat ./records/$locale/shop.sql >> update_tables.sql
cat ./records/$locale/skills.sql >> update_tables.sql
cat ./records/$locale/spawnlist.sql >> update_tables.sql
cat ./records/$locale/spawnlist_boss.sql >> update_tables.sql
cat ./records/$locale/spawnlist_door.sql >> update_tables.sql
cat ./records/$locale/spawnlist_light.sql >> update_tables.sql
cat ./records/$locale/spawnlist_npc.sql >> update_tables.sql
cat ./records/$locale/spawnlist_time.sql >> update_tables.sql
cat ./records/$locale/spawnlist_trap.sql >> update_tables.sql
cat ./records/$locale/spawnlist_ub.sql >> update_tables.sql
cat ./records/$locale/spr_action.sql >> update_tables.sql
cat ./records/$locale/trap.sql >> update_tables.sql
cat ./records/$locale/ub_managers.sql >> update_tables.sql
cat ./records/$locale/ub_settings.sql >> update_tables.sql
cat ./records/$locale/ub_times.sql >> update_tables.sql
cat ./records/$locale/weapon.sql >> update_tables.sql
cat ./records/$locale/weapon_skill.sql >> update_tables.sql
