#!/bin/bash
cat ./japanese/armor.sql > update_tables.sql
cat ./japanese/armor_set.sql >> update_tables.sql
cat ./japanese/beginner_items.sql >> update_tables.sql
cat ./japanese/commands.sql >> update_tables.sql
cat ./japanese/cooking_ingredients.sql >> update_tables.sql
cat ./japanese/cooking_recipes.sql >> update_tables.sql
cat ./japanese/door_gfxs.sql >> update_tables.sql
cat ./japanese/drop_item.sql >> update_tables.sql
cat ./japanese/droplist.sql >> update_tables.sql
cat ./japanese/dungeon.sql >> update_tables.sql
cat ./japanese/dungeon_random.sql >> update_tables.sql
cat ./japanese/etcitem.sql >> update_tables.sql
cat ./japanese/getback.sql >> update_tables.sql
cat ./japanese/getback_restart.sql >> update_tables.sql
cat ./japanese/magic_doll.sql >> update_tables.sql
cat ./japanese/mapids.sql >> update_tables.sql
cat ./japanese/mobgroup.sql >> update_tables.sql
cat ./japanese/mobskill.sql >> update_tables.sql
cat ./japanese/npc.sql >> update_tables.sql
cat ./japanese/npcaction.sql >> update_tables.sql
cat ./japanese/npcchat.sql >> update_tables.sql
cat ./japanese/petitem.sql >> update_tables.sql
cat ./japanese/pettypes.sql >> update_tables.sql
cat ./japanese/polymorphs.sql >> update_tables.sql
cat ./japanese/resolvent.sql >> update_tables.sql
cat ./japanese/shop.sql >> update_tables.sql
cat ./japanese/skills.sql >> update_tables.sql
cat ./japanese/spawnlist.sql >> update_tables.sql
cat ./japanese/spawnlist_boss.sql >> update_tables.sql
cat ./japanese/spawnlist_door.sql >> update_tables.sql
cat ./japanese/spawnlist_furniture.sql >> update_tables.sql
cat ./japanese/spawnlist_light.sql >> update_tables.sql
cat ./japanese/spawnlist_npc.sql >> update_tables.sql
cat ./japanese/spawnlist_time.sql >> update_tables.sql
cat ./japanese/spawnlist_trap.sql >> update_tables.sql
cat ./japanese/spawnlist_ub.sql >> update_tables.sql
cat ./japanese/spr_action.sql >> update_tables.sql
cat ./japanese/trap.sql >> update_tables.sql
cat ./japanese/ub_managers.sql >> update_tables.sql
cat ./japanese/ub_settings.sql >> update_tables.sql
cat ./japanese/ub_times.sql >> update_tables.sql
cat ./japanese/weapon.sql >> update_tables.sql
cat ./japanese/weapon_skill.sql >> update_tables.sql
