#!/bin/bash
cat ./english/accounts.sql > create_tables.sql
cat ./english/armor.sql >> create_tables.sql
cat ./english/armor_set.sql >> create_tables.sql
cat ./english/ban_ip.sql >> create_tables.sql
cat ./english/beginner_items.sql >> create_tables.sql
cat ./english/board.sql >> create_tables.sql
cat ./english/board_auction.sql >> create_tables.sql
cat ./english/castle.sql >> create_tables.sql
cat ./english/character_buddys.sql >> create_tables.sql
cat ./english/character_buffs.sql >> create_tables.sql
cat ./english/character_config.sql >> create_tables.sql
cat ./english/character_quests.sql >> create_tables.sql
cat ./english/character_skills.sql >> create_tables.sql
cat ./english/character_teleport.sql >> create_tables.sql
cat ./english/characters.sql >> create_tables.sql
cat ./english/clan_data.sql >> create_tables.sql
cat ./english/commands.sql >> create_tables.sql
cat ./english/cooking_ingredients.sql >> create_tables.sql
cat ./english/cooking_recipes.sql >> create_tables.sql
cat ./english/door_gfxs.sql >> create_tables.sql
cat ./english/drop_item.sql >> create_tables.sql
cat ./english/droplist.sql >> create_tables.sql
cat ./english/dungeon.sql >> create_tables.sql
cat ./english/dungeon_random.sql >> create_tables.sql
cat ./english/etcitem.sql >> create_tables.sql
cat ./english/getback.sql >> create_tables.sql
cat ./english/getback_restart.sql >> create_tables.sql
cat ./english/house.sql >> create_tables.sql
cat ./english/inn.sql >> create_tables.sql
cat ./english/inn_key.sql >> create_tables.sql
cat ./english/inventory_items.sql >> create_tables.sql
cat ./english/letter.sql >> create_tables.sql
cat ./english/log_accelerator.sql >> create_tables.sql
cat ./english/log_chat.sql >> create_tables.sql
cat ./english/log_enchant.sql >> create_tables.sql
cat ./english/magic_doll.sql >> create_tables.sql
cat ./english/mail.sql >> create_tables.sql
cat ./english/mapids.sql >> create_tables.sql
cat ./english/map_timer.sql >> create_tables.sql
cat ./english/mobgroup.sql >> create_tables.sql
cat ./english/mobskill.sql >> create_tables.sql
cat ./english/npc.sql >> create_tables.sql
cat ./english/npcaction.sql >> create_tables.sql
cat ./english/npcchat.sql >> create_tables.sql
cat ./english/petitem.sql >> create_tables.sql
cat ./english/pets.sql >> create_tables.sql
cat ./english/pettypes.sql >> create_tables.sql
cat ./english/polymorphs.sql >> create_tables.sql
cat ./english/race_ticket.sql >> create_tables.sql
cat ./english/resolvent.sql >> create_tables.sql
cat ./english/shop.sql >> create_tables.sql
cat ./english/skills.sql >> create_tables.sql
cat ./english/spawnlist.sql >> create_tables.sql
cat ./english/spawnlist_boss.sql >> create_tables.sql
cat ./english/spawnlist_door.sql >> create_tables.sql
cat ./english/spawnlist_furniture.sql >> create_tables.sql
cat ./english/spawnlist_light.sql >> create_tables.sql
cat ./english/spawnlist_npc.sql >> create_tables.sql
cat ./english/spawnlist_time.sql >> create_tables.sql
cat ./english/spawnlist_trap.sql >> create_tables.sql
cat ./english/spawnlist_ub.sql >> create_tables.sql
cat ./english/spr_action.sql >> create_tables.sql
cat ./english/town.sql >> create_tables.sql
cat ./english/trap.sql >> create_tables.sql
cat ./english/ub_managers.sql >> create_tables.sql
cat ./english/ub_settings.sql >> create_tables.sql
cat ./english/ub_times.sql >> create_tables.sql
cat ./english/weapon.sql >> create_tables.sql
cat ./english/weapon_skill.sql >> create_tables.sql
