type .\taiwanese\armor.sql > update_tables.sql
type .\taiwanese\armor_set.sql >> update_tables.sql
type .\taiwanese\beginner_items.sql >> update_tables.sql
type .\taiwanese\commands.sql >> update_tables.sql
type .\taiwanese\cooking_ingredients.sql >> update_tables.sql
type .\taiwanese\cooking_recipes.sql >> update_tables.sql
type .\taiwanese\door_gfxs.sql >> update_tables.sql
type .\taiwanese\drop_item.sql >> update_tables.sql
type .\taiwanese\droplist.sql >> update_tables.sql
type .\taiwanese\dungeon.sql >> update_tables.sql
type .\taiwanese\dungeon_random.sql >> update_tables.sql
type .\taiwanese\etcitem.sql >> update_tables.sql
type .\taiwanese\getback.sql >> update_tables.sql
type .\taiwanese\getback_restart.sql >> update_tables.sql
type .\taiwanese\magic_doll.sql >> update_tables.sql
type .\taiwanese\mapids.sql >> update_tables.sql
type .\taiwanese\mobgroup.sql >> update_tables.sql
type .\taiwanese\mobskill.sql >> update_tables.sql
type .\taiwanese\npc.sql >> update_tables.sql
type .\taiwanese\npcaction.sql >> update_tables.sql
type .\taiwanese\npcchat.sql >> update_tables.sql
type .\taiwanese\petitem.sql >> update_tables.sql
type .\taiwanese\pettypes.sql >> update_tables.sql
type .\taiwanese\polymorphs.sql >> update_tables.sql
type .\taiwanese\resolvent.sql >> update_tables.sql
type .\taiwanese\shop.sql >> update_tables.sql
type .\taiwanese\skills.sql >> update_tables.sql
type .\taiwanese\spawnlist.sql >> update_tables.sql
type .\taiwanese\spawnlist_boss.sql >> update_tables.sql
type .\taiwanese\spawnlist_door.sql >> update_tables.sql
type .\taiwanese\spawnlist_furniture.sql >> update_tables.sql
type .\taiwanese\spawnlist_light.sql >> update_tables.sql
type .\taiwanese\spawnlist_npc.sql >> update_tables.sql
type .\taiwanese\spawnlist_time.sql >> update_tables.sql
type .\taiwanese\spawnlist_trap.sql >> update_tables.sql
type .\taiwanese\spawnlist_ub.sql >> update_tables.sql
type .\taiwanese\spr_action.sql >> update_tables.sql
type .\taiwanese\trap.sql >> update_tables.sql
type .\taiwanese\ub_managers.sql >> update_tables.sql
type .\taiwanese\ub_settings.sql >> update_tables.sql
type .\taiwanese\ub_times.sql >> update_tables.sql
type .\taiwanese\weapon.sql >> update_tables.sql
type .\taiwanese\weapon_skill.sql >> update_tables.sql
