set dirpath=.\ja
type %dirpath%\accounts.sql > create_tables.sql
type %dirpath%\armor.sql >> create_tables.sql
type %dirpath%\armor_set.sql >> create_tables.sql
type %dirpath%\ban_ip.sql >> create_tables.sql
type %dirpath%\beginner_items.sql >> create_tables.sql
type %dirpath%\board.sql >> create_tables.sql
type %dirpath%\board_auction.sql >> create_tables.sql
type %dirpath%\castle.sql >> create_tables.sql
type %dirpath%\character_buddys.sql >> create_tables.sql
type %dirpath%\character_buffs.sql >> create_tables.sql
type %dirpath%\character_config.sql >> create_tables.sql
type %dirpath%\character_quests.sql >> create_tables.sql
type %dirpath%\character_skills.sql >> create_tables.sql
type %dirpath%\character_teleport.sql >> create_tables.sql
type %dirpath%\characters.sql >> create_tables.sql
type %dirpath%\clan_data.sql >> create_tables.sql
type %dirpath%\commands.sql >> create_tables.sql
type %dirpath%\cooking_ingredients.sql >> create_tables.sql
type %dirpath%\cooking_recipes.sql >> create_tables.sql
type %dirpath%\door_gfxs.sql >> create_tables.sql
type %dirpath%\drop_item.sql >> create_tables.sql
type %dirpath%\droplist.sql >> create_tables.sql
type %dirpath%\dungeon.sql >> create_tables.sql
type %dirpath%\dungeon_random.sql >> create_tables.sql
type %dirpath%\etcitem.sql >> create_tables.sql
type %dirpath%\getback.sql >> create_tables.sql
type %dirpath%\getback_restart.sql >> create_tables.sql
type %dirpath%\house.sql >> create_tables.sql
type %dirpath%\inn.sql >> create_tables.sql
type %dirpath%\inn_key.sql >> create_tables.sql
type %dirpath%\inventory_items.sql >> create_tables.sql
type %dirpath%\letter.sql >> create_tables.sql
type %dirpath%\log_accelerator.sql >> create_tables.sql
type %dirpath%\log_chat.sql >> create_tables.sql
type %dirpath%\log_enchant.sql >> create_tables.sql
type %dirpath%\magic_doll.sql >> create_tables.sql
type %dirpath%\mail.sql >> create_tables.sql
type %dirpath%\mapids.sql >> create_tables.sql
type %dirpath%\map_timer.sql >> create_tables.sql
type %dirpath%\mobgroup.sql >> create_tables.sql
type %dirpath%\mobskill.sql >> create_tables.sql
type %dirpath%\npc.sql >> create_tables.sql
type %dirpath%\npcaction.sql >> create_tables.sql
type %dirpath%\npcchat.sql >> create_tables.sql
type %dirpath%\petitem.sql >> create_tables.sql
type %dirpath%\pets.sql >> create_tables.sql
type %dirpath%\pettypes.sql >> create_tables.sql
type %dirpath%\polymorphs.sql >> create_tables.sql
type %dirpath%\race_ticket.sql >> create_tables.sql
type %dirpath%\resolvent.sql >> create_tables.sql
type %dirpath%\shop.sql >> create_tables.sql
type %dirpath%\skills.sql >> create_tables.sql
type %dirpath%\spawnlist.sql >> create_tables.sql
type %dirpath%\spawnlist_boss.sql >> create_tables.sql
type %dirpath%\spawnlist_door.sql >> create_tables.sql
type %dirpath%\spawnlist_furniture.sql >> create_tables.sql
type %dirpath%\spawnlist_light.sql >> create_tables.sql
type %dirpath%\spawnlist_npc.sql >> create_tables.sql
type %dirpath%\spawnlist_time.sql >> create_tables.sql
type %dirpath%\spawnlist_trap.sql >> create_tables.sql
type %dirpath%\spawnlist_ub.sql >> create_tables.sql
type %dirpath%\spr_action.sql >> create_tables.sql
type %dirpath%\town.sql >> create_tables.sql
type %dirpath%\trap.sql >> create_tables.sql
type %dirpath%\ub_managers.sql >> create_tables.sql
type %dirpath%\ub_settings.sql >> create_tables.sql
type %dirpath%\ub_times.sql >> create_tables.sql
type %dirpath%\weapon.sql >> create_tables.sql
type %dirpath%\weapon_skill.sql >> create_tables.sql
