set driver=mysql
set locale=ja
type .\schema\%driver%\armors.sql > update_tables.sql
type .\schema\%driver%\armor_sets.sql >> update_tables.sql
type .\schema\%driver%\beginner_items.sql >> update_tables.sql
type .\schema\%driver%\commands.sql >> update_tables.sql
type .\schema\%driver%\cooking_ingredients.sql >> update_tables.sql
type .\schema\%driver%\cooking_recipes.sql >> update_tables.sql
type .\schema\%driver%\door_gfxs.sql >> update_tables.sql
type .\schema\%driver%\drop_rates.sql >> update_tables.sql
type .\schema\%driver%\drop_items.sql >> update_tables.sql
type .\schema\%driver%\dungeons.sql >> update_tables.sql
type .\schema\%driver%\dungeon_random.sql >> update_tables.sql
type .\schema\%driver%\etc_items.sql >> update_tables.sql
type .\schema\%driver%\item_rates.sql >> update_tables.sql
type .\schema\%driver%\return_locations.sql >> update_tables.sql
type .\schema\%driver%\restart_locations.sql >> update_tables.sql
type .\schema\%driver%\magic_dolls.sql >> update_tables.sql
type .\schema\%driver%\map_ids.sql >> update_tables.sql
type .\schema\%driver%\mob_groups.sql >> update_tables.sql
type .\schema\%driver%\mob_skills.sql >> update_tables.sql
type .\schema\%driver%\npc.sql >> update_tables.sql
type .\schema\%driver%\npc_actions.sql >> update_tables.sql
type .\schema\%driver%\npc_chats.sql >> update_tables.sql
type .\schema\%driver%\pet_items.sql >> update_tables.sql
type .\schema\%driver%\pet_types.sql >> update_tables.sql
type .\schema\%driver%\polymorphs.sql >> update_tables.sql
type .\schema\%driver%\resolvents.sql >> update_tables.sql
type .\schema\%driver%\shops.sql >> update_tables.sql
type .\schema\%driver%\skills.sql >> update_tables.sql
type .\schema\%driver%\spawn_mobs.sql >> update_tables.sql
type .\schema\%driver%\spawn_boss.sql >> update_tables.sql
type .\schema\%driver%\spawn_doors.sql >> update_tables.sql
type .\schema\%driver%\spawn_lights.sql >> update_tables.sql
type .\schema\%driver%\spawn_npc.sql >> update_tables.sql
type .\schema\%driver%\spawn_times.sql >> update_tables.sql
type .\schema\%driver%\spawn_traps.sql >> update_tables.sql
type .\schema\%driver%\spawn_ub.sql >> update_tables.sql
type .\schema\%driver%\spr_actions.sql >> update_tables.sql
type .\schema\%driver%\traps.sql >> update_tables.sql
type .\schema\%driver%\ub_managers.sql >> update_tables.sql
type .\schema\%driver%\ub_settings.sql >> update_tables.sql
type .\schema\%driver%\ub_times.sql >> update_tables.sql
type .\schema\%driver%\weapons.sql >> update_tables.sql
type .\schema\%driver%\weapon_skills.sql >> update_tables.sql
type .\records\%locale%\armors.sql >> update_tables.sql
type .\records\%locale%\armor_sets.sql >> update_tables.sql
type .\records\%locale%\beginner_items.sql >> update_tables.sql
type .\records\%locale%\commands.sql >> update_tables.sql
type .\records\%locale%\cooking_ingredients.sql >> update_tables.sql
type .\records\%locale%\cooking_recipes.sql >> update_tables.sql
type .\records\%locale%\door_gfxs.sql >> update_tables.sql
type .\records\%locale%\drop_rates.sql >> update_tables.sql
type .\records\%locale%\drop_items.sql >> update_tables.sql
type .\records\%locale%\dungeons.sql >> update_tables.sql
type .\records\%locale%\dungeon_random.sql >> update_tables.sql
type .\records\%locale%\etc_items.sql >> update_tables.sql
type .\records\%locale%\item_ratess.sql >> update_tables.sql
type .\records\%locale%\return_locations.sql >> update_tables.sql
type .\records\%locale%\restart_locations.sql >> update_tables.sql
type .\records\%locale%\magic_dolls.sql >> update_tables.sql
type .\records\%locale%\map_ids.sql >> update_tables.sql
type .\records\%locale%\mob_groups.sql >> update_tables.sql
type .\records\%locale%\mob_skills.sql >> update_tables.sql
type .\records\%locale%\npc.sql >> update_tables.sql
type .\records\%locale%\npc_actions.sql >> update_tables.sql
type .\records\%locale%\npc_chats.sql >> update_tables.sql
type .\records\%locale%\pet_items.sql >> update_tables.sql
type .\records\%locale%\pet_types.sql >> update_tables.sql
type .\records\%locale%\polymorphs.sql >> update_tables.sql
type .\records\%locale%\resolvents.sql >> update_tables.sql
type .\records\%locale%\shops.sql >> update_tables.sql
type .\records\%locale%\skills.sql >> update_tables.sql
type .\records\%locale%\spawn_mobs.sql >> update_tables.sql
type .\records\%locale%\spawn_boss.sql >> update_tables.sql
type .\records\%locale%\spawn_doors.sql >> update_tables.sql
type .\records\%locale%\spawn_lights.sql >> update_tables.sql
type .\records\%locale%\spawn_npc.sql >> update_tables.sql
type .\records\%locale%\spawn_times.sql >> update_tables.sql
type .\records\%locale%\spawn_traps.sql >> update_tables.sql
type .\records\%locale%\spawn_ub.sql >> update_tables.sql
type .\records\%locale%\spr_actions.sql >> update_tables.sql
type .\records\%locale%\traps.sql >> update_tables.sql
type .\records\%locale%\ub_managers.sql >> update_tables.sql
type .\records\%locale%\ub_settings.sql >> update_tables.sql
type .\records\%locale%\ub_times.sql >> update_tables.sql
type .\records\%locale%\weapons.sql >> update_tables.sql
type .\records\%locale%\weapon_skills.sql >> update_tables.sql
