set dirpath=.\ja
type %dirpath%\armor.sql > update_tables.sql
type %dirpath%\armor_set.sql >> update_tables.sql
type %dirpath%\beginner_items.sql >> update_tables.sql
type %dirpath%\commands.sql >> update_tables.sql
type %dirpath%\cooking_ingredients.sql >> update_tables.sql
type %dirpath%\cooking_recipes.sql >> update_tables.sql
type %dirpath%\door_gfxs.sql >> update_tables.sql
type %dirpath%\drop_item.sql >> update_tables.sql
type %dirpath%\droplist.sql >> update_tables.sql
type %dirpath%\dungeon.sql >> update_tables.sql
type %dirpath%\dungeon_random.sql >> update_tables.sql
type %dirpath%\etcitem.sql >> update_tables.sql
type %dirpath%\getback.sql >> update_tables.sql
type %dirpath%\getback_restart.sql >> update_tables.sql
type %dirpath%\magic_doll.sql >> update_tables.sql
type %dirpath%\mapids.sql >> update_tables.sql
type %dirpath%\mobgroup.sql >> update_tables.sql
type %dirpath%\mobskill.sql >> update_tables.sql
type %dirpath%\npc.sql >> update_tables.sql
type %dirpath%\npcaction.sql >> update_tables.sql
type %dirpath%\npcchat.sql >> update_tables.sql
type %dirpath%\petitem.sql >> update_tables.sql
type %dirpath%\pettypes.sql >> update_tables.sql
type %dirpath%\polymorphs.sql >> update_tables.sql
type %dirpath%\resolvent.sql >> update_tables.sql
type %dirpath%\shop.sql >> update_tables.sql
type %dirpath%\skills.sql >> update_tables.sql
type %dirpath%\spawnlist.sql >> update_tables.sql
type %dirpath%\spawnlist_boss.sql >> update_tables.sql
type %dirpath%\spawnlist_door.sql >> update_tables.sql
type %dirpath%\spawnlist_furniture.sql >> update_tables.sql
type %dirpath%\spawnlist_light.sql >> update_tables.sql
type %dirpath%\spawnlist_npc.sql >> update_tables.sql
type %dirpath%\spawnlist_time.sql >> update_tables.sql
type %dirpath%\spawnlist_trap.sql >> update_tables.sql
type %dirpath%\spawnlist_ub.sql >> update_tables.sql
type %dirpath%\spr_action.sql >> update_tables.sql
type %dirpath%\trap.sql >> update_tables.sql
type %dirpath%\ub_managers.sql >> update_tables.sql
type %dirpath%\ub_settings.sql >> update_tables.sql
type %dirpath%\ub_times.sql >> update_tables.sql
type %dirpath%\weapon.sql >> update_tables.sql
type %dirpath%\weapon_skill.sql >> update_tables.sql
