#!/bin/bash
cat ./english/armor.sql > update_tables.sql
cat ./english/armor_set.sql >> update_tables.sql
cat ./english/beginner_items.sql >> update_tables.sql
cat ./english/commands.sql >> update_tables.sql
cat ./english/cooking_ingredients.sql >> update_tables.sql
cat ./english/cooking_recipes.sql >> update_tables.sql
cat ./english/door_gfxs.sql >> update_tables.sql
cat ./english/drop_item.sql >> update_tables.sql
cat ./english/droplist.sql >> update_tables.sql
cat ./english/dungeon.sql >> update_tables.sql
cat ./english/dungeon_random.sql >> update_tables.sql
cat ./english/etcitem.sql >> update_tables.sql
cat ./english/getback.sql >> update_tables.sql
cat ./english/getback_restart.sql >> update_tables.sql
cat ./english/magic_doll.sql >> update_tables.sql
cat ./english/mapids.sql >> update_tables.sql
cat ./english/mobgroup.sql >> update_tables.sql
cat ./english/mobskill.sql >> update_tables.sql
cat ./english/npc.sql >> update_tables.sql
cat ./english/npcaction.sql >> update_tables.sql
cat ./english/npcchat.sql >> update_tables.sql
cat ./english/petitem.sql >> update_tables.sql
cat ./english/pettypes.sql >> update_tables.sql
cat ./english/polymorphs.sql >> update_tables.sql
cat ./english/resolvent.sql >> update_tables.sql
cat ./english/shop.sql >> update_tables.sql
cat ./english/skills.sql >> update_tables.sql
cat ./english/spawnlist.sql >> update_tables.sql
cat ./english/spawnlist_boss.sql >> update_tables.sql
cat ./english/spawnlist_door.sql >> update_tables.sql
cat ./english/spawnlist_furniture.sql >> update_tables.sql
cat ./english/spawnlist_light.sql >> update_tables.sql
cat ./english/spawnlist_npc.sql >> update_tables.sql
cat ./english/spawnlist_time.sql >> update_tables.sql
cat ./english/spawnlist_trap.sql >> update_tables.sql
cat ./english/spawnlist_ub.sql >> update_tables.sql
cat ./english/spr_action.sql >> update_tables.sql
cat ./english/trap.sql >> update_tables.sql
cat ./english/ub_managers.sql >> update_tables.sql
cat ./english/ub_settings.sql >> update_tables.sql
cat ./english/ub_times.sql >> update_tables.sql
cat ./english/weapon.sql >> update_tables.sql
cat ./english/weapon_skill.sql >> update_tables.sql
