type .\japanese\armor.sql > update_tables.sql
type .\japanese\armor_set.sql >> update_tables.sql
type .\japanese\beginner_items.sql >> update_tables.sql
type .\japanese\commands.sql >> update_tables.sql
type .\japanese\cooking_ingredients.sql >> update_tables.sql
type .\japanese\cooking_recipes.sql >> update_tables.sql
type .\japanese\door_gfxs.sql >> update_tables.sql
type .\japanese\drop_item.sql >> update_tables.sql
type .\japanese\droplist.sql >> update_tables.sql
type .\japanese\dungeon.sql >> update_tables.sql
type .\japanese\dungeon_random.sql >> update_tables.sql
type .\japanese\etcitem.sql >> update_tables.sql
type .\japanese\getback.sql >> update_tables.sql
type .\japanese\getback_restart.sql >> update_tables.sql
type .\japanese\magic_doll.sql >> update_tables.sql
type .\japanese\mapids.sql >> update_tables.sql
type .\japanese\mobgroup.sql >> update_tables.sql
type .\japanese\mobskill.sql >> update_tables.sql
type .\japanese\npc.sql >> update_tables.sql
type .\japanese\npcaction.sql >> update_tables.sql
type .\japanese\npcchat.sql >> update_tables.sql
type .\japanese\petitem.sql >> update_tables.sql
type .\japanese\pettypes.sql >> update_tables.sql
type .\japanese\polymorphs.sql >> update_tables.sql
type .\japanese\resolvent.sql >> update_tables.sql
type .\japanese\shop.sql >> update_tables.sql
type .\japanese\skills.sql >> update_tables.sql
type .\japanese\spawnlist.sql >> update_tables.sql
type .\japanese\spawnlist_boss.sql >> update_tables.sql
type .\japanese\spawnlist_door.sql >> update_tables.sql
type .\japanese\spawnlist_furniture.sql >> update_tables.sql
type .\japanese\spawnlist_light.sql >> update_tables.sql
type .\japanese\spawnlist_npc.sql >> update_tables.sql
type .\japanese\spawnlist_time.sql >> update_tables.sql
type .\japanese\spawnlist_trap.sql >> update_tables.sql
type .\japanese\spawnlist_ub.sql >> update_tables.sql
type .\japanese\spr_action.sql >> update_tables.sql
type .\japanese\trap.sql >> update_tables.sql
type .\japanese\ub_managers.sql >> update_tables.sql
type .\japanese\ub_settings.sql >> update_tables.sql
type .\japanese\ub_times.sql >> update_tables.sql
type .\japanese\weapon.sql >> update_tables.sql
type .\japanese\weapon_skill.sql >> update_tables.sql
