#!/bin/bash
cat ./taiwanese/armor.sql > update_tables.sql
cat ./taiwanese/armor_set.sql >> update_tables.sql
cat ./taiwanese/beginner_items.sql >> update_tables.sql
cat ./taiwanese/commands.sql >> update_tables.sql
cat ./taiwanese/cooking_ingredients.sql >> update_tables.sql
cat ./taiwanese/cooking_recipes.sql >> update_tables.sql
cat ./taiwanese/door_gfxs.sql >> update_tables.sql
cat ./taiwanese/drop_item.sql >> update_tables.sql
cat ./taiwanese/droplist.sql >> update_tables.sql
cat ./taiwanese/dungeon.sql >> update_tables.sql
cat ./taiwanese/dungeon_random.sql >> update_tables.sql
cat ./taiwanese/etcitem.sql >> update_tables.sql
cat ./taiwanese/getback.sql >> update_tables.sql
cat ./taiwanese/getback_restart.sql >> update_tables.sql
cat ./taiwanese/magic_doll.sql >> update_tables.sql
cat ./taiwanese/mapids.sql >> update_tables.sql
cat ./taiwanese/mobgroup.sql >> update_tables.sql
cat ./taiwanese/mobskill.sql >> update_tables.sql
cat ./taiwanese/npc.sql >> update_tables.sql
cat ./taiwanese/npcaction.sql >> update_tables.sql
cat ./taiwanese/npcchat.sql >> update_tables.sql
cat ./taiwanese/petitem.sql >> update_tables.sql
cat ./taiwanese/pettypes.sql >> update_tables.sql
cat ./taiwanese/polymorphs.sql >> update_tables.sql
cat ./taiwanese/resolvent.sql >> update_tables.sql
cat ./taiwanese/shop.sql >> update_tables.sql
cat ./taiwanese/skills.sql >> update_tables.sql
cat ./taiwanese/spawnlist.sql >> update_tables.sql
cat ./taiwanese/spawnlist_boss.sql >> update_tables.sql
cat ./taiwanese/spawnlist_door.sql >> update_tables.sql
cat ./taiwanese/spawnlist_furniture.sql >> update_tables.sql
cat ./taiwanese/spawnlist_light.sql >> update_tables.sql
cat ./taiwanese/spawnlist_npc.sql >> update_tables.sql
cat ./taiwanese/spawnlist_time.sql >> update_tables.sql
cat ./taiwanese/spawnlist_trap.sql >> update_tables.sql
cat ./taiwanese/spawnlist_ub.sql >> update_tables.sql
cat ./taiwanese/spr_action.sql >> update_tables.sql
cat ./taiwanese/trap.sql >> update_tables.sql
cat ./taiwanese/ub_managers.sql >> update_tables.sql
cat ./taiwanese/ub_settings.sql >> update_tables.sql
cat ./taiwanese/ub_times.sql >> update_tables.sql
cat ./taiwanese/weapon.sql >> update_tables.sql
cat ./taiwanese/weapon_skill.sql >> update_tables.sql
