type .\japanese\accounts.sql > create_tables.sql
type .\japanese\armor.sql >> create_tables.sql
type .\japanese\armor_set.sql >> create_tables.sql
type .\japanese\ban_ip.sql >> create_tables.sql
type .\japanese\beginner_items.sql >> create_tables.sql
type .\japanese\board.sql >> create_tables.sql
type .\japanese\board_auction.sql >> create_tables.sql
type .\japanese\castle.sql >> create_tables.sql
type .\japanese\character_buddys.sql >> create_tables.sql
type .\japanese\character_buffs.sql >> create_tables.sql
type .\japanese\character_config.sql >> create_tables.sql
type .\japanese\character_quests.sql >> create_tables.sql
type .\japanese\character_skills.sql >> create_tables.sql
type .\japanese\character_teleport.sql >> create_tables.sql
type .\japanese\characters.sql >> create_tables.sql
type .\japanese\clan_data.sql >> create_tables.sql
type .\japanese\commands.sql >> create_tables.sql
type .\japanese\cooking_ingredients.sql >> create_tables.sql
type .\japanese\cooking_recipes.sql >> create_tables.sql
type .\japanese\door_gfxs.sql >> create_tables.sql
type .\japanese\drop_item.sql >> create_tables.sql
type .\japanese\droplist.sql >> create_tables.sql
type .\japanese\dungeon.sql >> create_tables.sql
type .\japanese\dungeon_random.sql >> create_tables.sql
type .\japanese\etcitem.sql >> create_tables.sql
type .\japanese\getback.sql >> create_tables.sql
type .\japanese\getback_restart.sql >> create_tables.sql
type .\japanese\house.sql >> create_tables.sql
type .\japanese\inn.sql >> create_tables.sql
type .\japanese\inn_key.sql >> create_tables.sql
type .\japanese\inventory_items.sql >> create_tables.sql
type .\japanese\letter.sql >> create_tables.sql
type .\japanese\log_accelerator.sql >> create_tables.sql
type .\japanese\log_chat.sql >> create_tables.sql
type .\japanese\log_enchant.sql >> create_tables.sql
type .\japanese\magic_doll.sql >> create_tables.sql
type .\japanese\mail.sql >> create_tables.sql
type .\japanese\mapids.sql >> create_tables.sql
type .\japanese\map_timer.sql >> create_tables.sql
type .\japanese\mobgroup.sql >> create_tables.sql
type .\japanese\mobskill.sql >> create_tables.sql
type .\japanese\npc.sql >> create_tables.sql
type .\japanese\npcaction.sql >> create_tables.sql
type .\japanese\npcchat.sql >> create_tables.sql
type .\japanese\petitem.sql >> create_tables.sql
type .\japanese\pets.sql >> create_tables.sql
type .\japanese\pettypes.sql >> create_tables.sql
type .\japanese\polymorphs.sql >> create_tables.sql
type .\japanese\race_ticket.sql >> create_tables.sql
type .\japanese\resolvent.sql >> create_tables.sql
type .\japanese\shop.sql >> create_tables.sql
type .\japanese\skills.sql >> create_tables.sql
type .\japanese\spawnlist.sql >> create_tables.sql
type .\japanese\spawnlist_boss.sql >> create_tables.sql
type .\japanese\spawnlist_door.sql >> create_tables.sql
type .\japanese\spawnlist_furniture.sql >> create_tables.sql
type .\japanese\spawnlist_light.sql >> create_tables.sql
type .\japanese\spawnlist_npc.sql >> create_tables.sql
type .\japanese\spawnlist_time.sql >> create_tables.sql
type .\japanese\spawnlist_trap.sql >> create_tables.sql
type .\japanese\spawnlist_ub.sql >> create_tables.sql
type .\japanese\spr_action.sql >> create_tables.sql
type .\japanese\town.sql >> create_tables.sql
type .\japanese\trap.sql >> create_tables.sql
type .\japanese\ub_managers.sql >> create_tables.sql
type .\japanese\ub_settings.sql >> create_tables.sql
type .\japanese\ub_times.sql >> create_tables.sql
type .\japanese\weapon.sql >> create_tables.sql
type .\japanese\weapon_skill.sql >> create_tables.sql
