set driver=mysql
set locale=ja
if not exist .\templates md .\templates
type .\schema\%driver%\accounts.sql > .\templates\accounts.sql
type .\schema\%driver%\armor.sql > .\templates\armor.sql
type .\schema\%driver%\armor_set.sql > .\templates\armor_set.sql
type .\schema\%driver%\ban_ip.sql > .\templates\ban_ip.sql
type .\schema\%driver%\beginner_items.sql > .\templates\beginner_items.sql
type .\schema\%driver%\board.sql > .\templates\board.sql
type .\schema\%driver%\board_auction.sql > .\templates\board_auction.sql
type .\schema\%driver%\castle.sql > .\templates\castle.sql
type .\schema\%driver%\character_buddys.sql > .\templates\character_buddys.sql
type .\schema\%driver%\character_buffs.sql > .\templates\character_buffs.sql
type .\schema\%driver%\character_config.sql > .\templates\character_config.sql
type .\schema\%driver%\character_quests.sql > .\templates\character_quests.sql
type .\schema\%driver%\character_skills.sql > .\templates\character_skills.sql
type .\schema\%driver%\character_teleport.sql > .\templates\character_teleport.sql
type .\schema\%driver%\characters.sql > .\templates\characters.sql
type .\schema\%driver%\clan_data.sql > .\templates\clan_data.sql
type .\schema\%driver%\commands.sql > .\templates\commands.sql
type .\schema\%driver%\cooking_ingredients.sql > .\templates\cooking_ingredients.sql
type .\schema\%driver%\cooking_recipes.sql > .\templates\cooking_recipes.sql
type .\schema\%driver%\door_gfxs.sql > .\templates\door_gfxs.sql
type .\schema\%driver%\drop_item.sql > .\templates\drop_item.sql
type .\schema\%driver%\droplist.sql > .\templates\droplist.sql
type .\schema\%driver%\dungeon.sql > .\templates\dungeon.sql
type .\schema\%driver%\dungeon_random.sql > .\templates\dungeon_random.sql
type .\schema\%driver%\etcitem.sql > .\templates\etcitem.sql
type .\schema\%driver%\getback.sql > .\templates\getback.sql
type .\schema\%driver%\getback_restart.sql > .\templates\getback_restart.sql
type .\schema\%driver%\house.sql > .\templates\house.sql
type .\schema\%driver%\inn.sql > .\templates\inn.sql
type .\schema\%driver%\inn_key.sql > .\templates\inn_key.sql
type .\schema\%driver%\inventory_items.sql > .\templates\inventory_items.sql
type .\schema\%driver%\letter.sql > .\templates\letter.sql
type .\schema\%driver%\log_accelerator.sql > .\templates\log_accelerator.sql
type .\schema\%driver%\log_chat.sql > .\templates\log_chat.sql
type .\schema\%driver%\log_enchant.sql > .\templates\log_enchant.sql
type .\schema\%driver%\magic_doll.sql > .\templates\magic_doll.sql
type .\schema\%driver%\mail.sql > .\templates\mail.sql
type .\schema\%driver%\mapids.sql > .\templates\mapids.sql
type .\schema\%driver%\map_timer.sql > .\templates\map_timer.sql
type .\schema\%driver%\mobgroup.sql > .\templates\mobgroup.sql
type .\schema\%driver%\mobskill.sql > .\templates\mobskill.sql
type .\schema\%driver%\npc.sql > .\templates\npc.sql
type .\schema\%driver%\npcaction.sql > .\templates\npcaction.sql
type .\schema\%driver%\npcchat.sql > .\templates\npcchat.sql
type .\schema\%driver%\petitem.sql > .\templates\petitem.sql
type .\schema\%driver%\pets.sql > .\templates\pets.sql
type .\schema\%driver%\pettypes.sql > .\templates\pettypes.sql
type .\schema\%driver%\polymorphs.sql > .\templates\polymorphs.sql
type .\schema\%driver%\race_ticket.sql > .\templates\race_ticket.sql
type .\schema\%driver%\resolvent.sql > .\templates\resolvent.sql
type .\schema\%driver%\shop.sql > .\templates\shop.sql
type .\schema\%driver%\skills.sql > .\templates\skills.sql
type .\schema\%driver%\spawnlist.sql > .\templates\spawnlist.sql
type .\schema\%driver%\spawnlist_boss.sql > .\templates\spawnlist_boss.sql
type .\schema\%driver%\spawnlist_door.sql > .\templates\spawnlist_door.sql
type .\schema\%driver%\spawnlist_furniture.sql > .\templates\spawnlist_furniture.sql
type .\schema\%driver%\spawnlist_light.sql > .\templates\spawnlist_light.sql
type .\schema\%driver%\spawnlist_npc.sql > .\templates\spawnlist_npc.sql
type .\schema\%driver%\spawnlist_time.sql > .\templates\spawnlist_time.sql
type .\schema\%driver%\spawnlist_trap.sql > .\templates\spawnlist_trap.sql
type .\schema\%driver%\spawnlist_ub.sql > .\templates\spawnlist_ub.sql
type .\schema\%driver%\spr_action.sql > .\templates\spr_action.sql
type .\schema\%driver%\town.sql > .\templates\town.sql
type .\schema\%driver%\trap.sql > .\templates\trap.sql
type .\schema\%driver%\ub_managers.sql > .\templates\ub_managers.sql
type .\schema\%driver%\ub_settings.sql > .\templates\ub_settings.sql
type .\schema\%driver%\ub_times.sql > .\templates\ub_times.sql
type .\schema\%driver%\weapon.sql > .\templates\weapon.sql
type .\schema\%driver%\weapon_skill.sql > .\templates\weapon_skill.sql
type .\records\%locale%\armor.sql >> .\templates\armor.sql
type .\records\%locale%\armor_set.sql >> .\templates\armor_set.sql
type .\records\%locale%\beginner_items.sql >> .\templates\beginner_items.sql
type .\records\%locale%\board_auction.sql >> .\templates\board_auction.sql
type .\records\%locale%\castle.sql >> .\templates\castle.sql
type .\records\%locale%\commands.sql >> .\templates\commands.sql
type .\records\%locale%\cooking_ingredients.sql >> .\templates\cooking_ingredients.sql
type .\records\%locale%\cooking_recipes.sql >> .\templates\cooking_recipes.sql
type .\records\%locale%\door_gfxs.sql >> .\templates\door_gfxs.sql
type .\records\%locale%\drop_item.sql >> .\templates\drop_item.sql
type .\records\%locale%\droplist.sql >> .\templates\droplist.sql
type .\records\%locale%\dungeon.sql >> .\templates\dungeon.sql
type .\records\%locale%\dungeon_random.sql >> .\templates\dungeon_random.sql
type .\records\%locale%\etcitem.sql >> .\templates\etcitem.sql
type .\records\%locale%\getback.sql >> .\templates\getback.sql
type .\records\%locale%\getback_restart.sql >> .\templates\getback_restart.sql
type .\records\%locale%\house.sql >> .\templates\house.sql
type .\records\%locale%\inn.sql >> .\templates\inn.sql
type .\records\%locale%\magic_doll.sql >> .\templates\magic_doll.sql
type .\records\%locale%\mapids.sql >> .\templates\mapids.sql
type .\records\%locale%\mobgroup.sql >> .\templates\mobgroup.sql
type .\records\%locale%\mobskill.sql >> .\templates\mobskill.sql
type .\records\%locale%\npc.sql >> .\templates\npc.sql
type .\records\%locale%\npcaction.sql >> .\templates\npcaction.sql
type .\records\%locale%\npcchat.sql >> .\templates\npcchat.sql
type .\records\%locale%\petitem.sql >> .\templates\petitem.sql
type .\records\%locale%\pettypes.sql >> .\templates\pettypes.sql
type .\records\%locale%\polymorphs.sql >> .\templates\polymorphs.sql
type .\records\%locale%\resolvent.sql >> .\templates\resolvent.sql
type .\records\%locale%\shop.sql >> .\templates\shop.sql
type .\records\%locale%\skills.sql >> .\templates\skills.sql
type .\records\%locale%\spawnlist.sql >> .\templates\spawnlist.sql
type .\records\%locale%\spawnlist_boss.sql >> .\templates\spawnlist_boss.sql
type .\records\%locale%\spawnlist_door.sql >> .\templates\spawnlist_door.sql
type .\records\%locale%\spawnlist_light.sql >> .\templates\spawnlist_light.sql
type .\records\%locale%\spawnlist_npc.sql >> .\templates\spawnlist_npc.sql
type .\records\%locale%\spawnlist_time.sql >> .\templates\spawnlist_time.sql
type .\records\%locale%\spawnlist_trap.sql >> .\templates\spawnlist_trap.sql
type .\records\%locale%\spawnlist_ub.sql >> .\templates\spawnlist_ub.sql
type .\records\%locale%\spr_action.sql >> .\templates\spr_action.sql
type .\records\%locale%\town.sql >> .\templates\town.sql
type .\records\%locale%\trap.sql >> .\templates\trap.sql
type .\records\%locale%\ub_managers.sql >> .\templates\ub_managers.sql
type .\records\%locale%\ub_settings.sql >> .\templates\ub_settings.sql
type .\records\%locale%\ub_times.sql >> .\templates\ub_times.sql
type .\records\%locale%\weapon.sql >> .\templates\weapon.sql
type .\records\%locale%\weapon_skill.sql >> .\templates\weapon_skill.sql
