#!/bin/bash
driver='mysql'
locale='ja'
cat ./schema/$driver/armors.sql > update_tables.sql
cat ./schema/$driver/armor_sets.sql >> update_tables.sql
cat ./schema/$driver/beginner_items.sql >> update_tables.sql
cat ./schema/$driver/commands.sql >> update_tables.sql
cat ./schema/$driver/cooking_ingredients.sql >> update_tables.sql
cat ./schema/$driver/cooking_recipes.sql >> update_tables.sql
cat ./schema/$driver/door_gfxs.sql >> update_tables.sql
cat ./schema/$driver/drop_rates.sql >> update_tables.sql
cat ./schema/$driver/drop_items.sql >> update_tables.sql
cat ./schema/$driver/dungeons.sql >> update_tables.sql
cat ./schema/$driver/dungeon_random.sql >> update_tables.sql
cat ./schema/$driver/etc_items.sql >> update_tables.sql
cat ./schema/$driver/return_locations.sql >> update_tables.sql
cat ./schema/$driver/restart_locations.sql >> update_tables.sql
cat ./schema/$driver/magic_dolls.sql >> update_tables.sql
cat ./schema/$driver/map_ids.sql >> update_tables.sql
cat ./schema/$driver/mob_groups.sql >> update_tables.sql
cat ./schema/$driver/mob_skills.sql >> update_tables.sql
cat ./schema/$driver/npc.sql >> update_tables.sql
cat ./schema/$driver/npc_actions.sql >> update_tables.sql
cat ./schema/$driver/npc_chats.sql >> update_tables.sql
cat ./schema/$driver/pet_items.sql >> update_tables.sql
cat ./schema/$driver/pet_types.sql >> update_tables.sql
cat ./schema/$driver/polymorphs.sql >> update_tables.sql
cat ./schema/$driver/resolvents.sql >> update_tables.sql
cat ./schema/$driver/shops.sql >> update_tables.sql
cat ./schema/$driver/skills.sql >> update_tables.sql
cat ./schema/$driver/spawn_mobs.sql >> update_tables.sql
cat ./schema/$driver/spawn_boss.sql >> update_tables.sql
cat ./schema/$driver/spawn_doors.sql >> update_tables.sql
cat ./schema/$driver/spawn_lights.sql >> update_tables.sql
cat ./schema/$driver/spawn_npc.sql >> update_tables.sql
cat ./schema/$driver/spawn_times.sql >> update_tables.sql
cat ./schema/$driver/spawn_traps.sql >> update_tables.sql
cat ./schema/$driver/spawn_ub.sql >> update_tables.sql
cat ./schema/$driver/spr_actions.sql >> update_tables.sql
cat ./schema/$driver/traps.sql >> update_tables.sql
cat ./schema/$driver/ub_managers.sql >> update_tables.sql
cat ./schema/$driver/ub_settings.sql >> update_tables.sql
cat ./schema/$driver/ub_times.sql >> update_tables.sql
cat ./schema/$driver/weapons.sql >> update_tables.sql
cat ./schema/$driver/weapon_skills.sql >> update_tables.sql
cat ./records/$locale/armors.sql >> update_tables.sql
cat ./records/$locale/armor_sets.sql >> update_tables.sql
cat ./records/$locale/beginner_items.sql >> update_tables.sql
cat ./records/$locale/commands.sql >> update_tables.sql
cat ./records/$locale/cooking_ingredients.sql >> update_tables.sql
cat ./records/$locale/cooking_recipes.sql >> update_tables.sql
cat ./records/$locale/door_gfxs.sql >> update_tables.sql
cat ./records/$locale/drop_rates.sql >> update_tables.sql
cat ./records/$locale/drop_items.sql >> update_tables.sql
cat ./records/$locale/dungeons.sql >> update_tables.sql
cat ./records/$locale/dungeon_random.sql >> update_tables.sql
cat ./records/$locale/etc_items.sql >> update_tables.sql
cat ./records/$locale/return_locations.sql >> update_tables.sql
cat ./records/$locale/restart_locations.sql >> update_tables.sql
cat ./records/$locale/magic_dolls.sql >> update_tables.sql
cat ./records/$locale/map_ids.sql >> update_tables.sql
cat ./records/$locale/mob_groups.sql >> update_tables.sql
cat ./records/$locale/mob_skills.sql >> update_tables.sql
cat ./records/$locale/npc.sql >> update_tables.sql
cat ./records/$locale/npc_actions.sql >> update_tables.sql
cat ./records/$locale/npc_chats.sql >> update_tables.sql
cat ./records/$locale/pet_items.sql >> update_tables.sql
cat ./records/$locale/pet_types.sql >> update_tables.sql
cat ./records/$locale/polymorphs.sql >> update_tables.sql
cat ./records/$locale/resolvents.sql >> update_tables.sql
cat ./records/$locale/shops.sql >> update_tables.sql
cat ./records/$locale/skills.sql >> update_tables.sql
cat ./records/$locale/spawn_mobs.sql >> update_tables.sql
cat ./records/$locale/spawn_boss.sql >> update_tables.sql
cat ./records/$locale/spawn_doors.sql >> update_tables.sql
cat ./records/$locale/spawn_lights.sql >> update_tables.sql
cat ./records/$locale/spawn_npc.sql >> update_tables.sql
cat ./records/$locale/spawn_times.sql >> update_tables.sql
cat ./records/$locale/spawn_traps.sql >> update_tables.sql
cat ./records/$locale/spawn_ub.sql >> update_tables.sql
cat ./records/$locale/spr_actions.sql >> update_tables.sql
cat ./records/$locale/traps.sql >> update_tables.sql
cat ./records/$locale/ub_managers.sql >> update_tables.sql
cat ./records/$locale/ub_settings.sql >> update_tables.sql
cat ./records/$locale/ub_times.sql >> update_tables.sql
cat ./records/$locale/weapons.sql >> update_tables.sql
cat ./records/$locale/weapon_skills.sql >> update_tables.sql
