type .\english\accounts.sql > create_tables.sql
type .\english\armor.sql >> create_tables.sql
type .\english\armor_set.sql >> create_tables.sql
type .\english\ban_ip.sql >> create_tables.sql
type .\english\beginner_items.sql >> create_tables.sql
type .\english\board.sql >> create_tables.sql
type .\english\board_auction.sql >> create_tables.sql
type .\english\castle.sql >> create_tables.sql
type .\english\character_buddys.sql >> create_tables.sql
type .\english\character_buffs.sql >> create_tables.sql
type .\english\character_config.sql >> create_tables.sql
type .\english\character_quests.sql >> create_tables.sql
type .\english\character_skills.sql >> create_tables.sql
type .\english\character_teleport.sql >> create_tables.sql
type .\english\characters.sql >> create_tables.sql
type .\english\clan_data.sql >> create_tables.sql
type .\english\commands.sql >> create_tables.sql
type .\english\cooking_ingredients.sql >> create_tables.sql
type .\english\cooking_recipes.sql >> create_tables.sql
type .\english\door_gfxs.sql >> create_tables.sql
type .\english\drop_item.sql >> create_tables.sql
type .\english\droplist.sql >> create_tables.sql
type .\english\dungeon.sql >> create_tables.sql
type .\english\dungeon_random.sql >> create_tables.sql
type .\english\etcitem.sql >> create_tables.sql
type .\english\getback.sql >> create_tables.sql
type .\english\getback_restart.sql >> create_tables.sql
type .\english\house.sql >> create_tables.sql
type .\english\inn.sql >> create_tables.sql
type .\english\inn_key.sql >> create_tables.sql
type .\english\inventory_items.sql >> create_tables.sql
type .\english\letter.sql >> create_tables.sql
type .\english\log_accelerator.sql >> create_tables.sql
type .\english\log_chat.sql >> create_tables.sql
type .\english\log_enchant.sql >> create_tables.sql
type .\english\magic_doll.sql >> create_tables.sql
type .\english\mail.sql >> create_tables.sql
type .\english\mapids.sql >> create_tables.sql
type .\english\map_timer.sql >> create_tables.sql
type .\english\mobgroup.sql >> create_tables.sql
type .\english\mobskill.sql >> create_tables.sql
type .\english\npc.sql >> create_tables.sql
type .\english\npcaction.sql >> create_tables.sql
type .\english\npcchat.sql >> create_tables.sql
type .\english\petitem.sql >> create_tables.sql
type .\english\pets.sql >> create_tables.sql
type .\english\pettypes.sql >> create_tables.sql
type .\english\polymorphs.sql >> create_tables.sql
type .\english\race_ticket.sql >> create_tables.sql
type .\english\resolvent.sql >> create_tables.sql
type .\english\shop.sql >> create_tables.sql
type .\english\skills.sql >> create_tables.sql
type .\english\spawnlist.sql >> create_tables.sql
type .\english\spawnlist_boss.sql >> create_tables.sql
type .\english\spawnlist_door.sql >> create_tables.sql
type .\english\spawnlist_furniture.sql >> create_tables.sql
type .\english\spawnlist_light.sql >> create_tables.sql
type .\english\spawnlist_npc.sql >> create_tables.sql
type .\english\spawnlist_time.sql >> create_tables.sql
type .\english\spawnlist_trap.sql >> create_tables.sql
type .\english\spawnlist_ub.sql >> create_tables.sql
type .\english\spr_action.sql >> create_tables.sql
type .\english\town.sql >> create_tables.sql
type .\english\trap.sql >> create_tables.sql
type .\english\ub_managers.sql >> create_tables.sql
type .\english\ub_settings.sql >> create_tables.sql
type .\english\ub_times.sql >> create_tables.sql
type .\english\weapon.sql >> create_tables.sql
type .\english\weapon_skill.sql >> create_tables.sql
