set driver=h2
set locale=ja
type .\schema\%driver%\accounts.sql > create_tables.sql
type .\schema\%driver%\armors.sql >> create_tables.sql
type .\schema\%driver%\armor_sets.sql >> create_tables.sql
type .\schema\%driver%\ban_ips.sql >> create_tables.sql
type .\schema\%driver%\beginner_items.sql >> create_tables.sql
type .\schema\%driver%\board.sql >> create_tables.sql
type .\schema\%driver%\house_auction.sql >> create_tables.sql
type .\schema\%driver%\castles.sql >> create_tables.sql
type .\schema\%driver%\character_buddys.sql >> create_tables.sql
type .\schema\%driver%\character_buffs.sql >> create_tables.sql
type .\schema\%driver%\character_configs.sql >> create_tables.sql
type .\schema\%driver%\character_quests.sql >> create_tables.sql
type .\schema\%driver%\character_skills.sql >> create_tables.sql
type .\schema\%driver%\character_bookmarks.sql >> create_tables.sql
type .\schema\%driver%\characters.sql >> create_tables.sql
type .\schema\%driver%\clans.sql >> create_tables.sql
type .\schema\%driver%\commands.sql >> create_tables.sql
type .\schema\%driver%\cooking_ingredients.sql >> create_tables.sql
type .\schema\%driver%\cooking_recipes.sql >> create_tables.sql
type .\schema\%driver%\door_gfxs.sql >> create_tables.sql
type .\schema\%driver%\drop_rates.sql >> create_tables.sql
type .\schema\%driver%\drop_items.sql >> create_tables.sql
type .\schema\%driver%\dungeons.sql >> create_tables.sql
type .\schema\%driver%\dungeon_random.sql >> create_tables.sql
type .\schema\%driver%\etc_items.sql >> create_tables.sql
type .\schema\%driver%\return_locations.sql >> create_tables.sql
type .\schema\%driver%\restart_locations.sql >> create_tables.sql
type .\schema\%driver%\houses.sql >> create_tables.sql
type .\schema\%driver%\inns.sql >> create_tables.sql
type .\schema\%driver%\inn_keys.sql >> create_tables.sql
type .\schema\%driver%\inventory_items.sql >> create_tables.sql
type .\schema\%driver%\letters.sql >> create_tables.sql
type .\schema\%driver%\log_accelerator.sql >> create_tables.sql
type .\schema\%driver%\log_chat.sql >> create_tables.sql
type .\schema\%driver%\log_enchant.sql >> create_tables.sql
type .\schema\%driver%\magic_dolls.sql >> create_tables.sql
type .\schema\%driver%\mails.sql >> create_tables.sql
type .\schema\%driver%\map_ids.sql >> create_tables.sql
type .\schema\%driver%\map_timers.sql >> create_tables.sql
type .\schema\%driver%\mob_groups.sql >> create_tables.sql
type .\schema\%driver%\mob_skills.sql >> create_tables.sql
type .\schema\%driver%\npc.sql >> create_tables.sql
type .\schema\%driver%\npc_actions.sql >> create_tables.sql
type .\schema\%driver%\npc_chats.sql >> create_tables.sql
type .\schema\%driver%\pet_items.sql >> create_tables.sql
type .\schema\%driver%\pets.sql >> create_tables.sql
type .\schema\%driver%\pet_types.sql >> create_tables.sql
type .\schema\%driver%\polymorphs.sql >> create_tables.sql
type .\schema\%driver%\race_tickets.sql >> create_tables.sql
type .\schema\%driver%\resolvents.sql >> create_tables.sql
type .\schema\%driver%\shops.sql >> create_tables.sql
type .\schema\%driver%\skills.sql >> create_tables.sql
type .\schema\%driver%\spawn_mobs.sql >> create_tables.sql
type .\schema\%driver%\spawn_boss.sql >> create_tables.sql
type .\schema\%driver%\spawn_doors.sql >> create_tables.sql
type .\schema\%driver%\spawn_furnitures.sql >> create_tables.sql
type .\schema\%driver%\spawn_lights.sql >> create_tables.sql
type .\schema\%driver%\spawn_npc.sql >> create_tables.sql
type .\schema\%driver%\spawn_times.sql >> create_tables.sql
type .\schema\%driver%\spawn_traps.sql >> create_tables.sql
type .\schema\%driver%\spawn_ub.sql >> create_tables.sql
type .\schema\%driver%\spr_actions.sql >> create_tables.sql
type .\schema\%driver%\towns.sql >> create_tables.sql
type .\schema\%driver%\traps.sql >> create_tables.sql
type .\schema\%driver%\ub_managers.sql >> create_tables.sql
type .\schema\%driver%\ub_settings.sql >> create_tables.sql
type .\schema\%driver%\ub_times.sql >> create_tables.sql
type .\schema\%driver%\weapons.sql >> create_tables.sql
type .\schema\%driver%\weapon_skills.sql >> create_tables.sql
type .\records\%locale%\armors.sql >> create_tables.sql
type .\records\%locale%\armor_sets.sql >> create_tables.sql
type .\records\%locale%\beginner_items.sql >> create_tables.sql
type .\records\%locale%\house_auction.sql >> create_tables.sql
type .\records\%locale%\castles.sql >> create_tables.sql
type .\records\%locale%\commands.sql >> create_tables.sql
type .\records\%locale%\cooking_ingredients.sql >> create_tables.sql
type .\records\%locale%\cooking_recipes.sql >> create_tables.sql
type .\records\%locale%\door_gfxs.sql >> create_tables.sql
type .\records\%locale%\drop_rates.sql >> create_tables.sql
type .\records\%locale%\drop_items.sql >> create_tables.sql
type .\records\%locale%\dungeons.sql >> create_tables.sql
type .\records\%locale%\dungeon_random.sql >> create_tables.sql
type .\records\%locale%\etc_items.sql >> create_tables.sql
type .\records\%locale%\return_locations.sql >> create_tables.sql
type .\records\%locale%\restart_locations.sql >> create_tables.sql
type .\records\%locale%\houses.sql >> create_tables.sql
type .\records\%locale%\inns.sql >> create_tables.sql
type .\records\%locale%\magic_dolls.sql >> create_tables.sql
type .\records\%locale%\map_ids.sql >> create_tables.sql
type .\records\%locale%\mob_groups.sql >> create_tables.sql
type .\records\%locale%\mob_skills.sql >> create_tables.sql
type .\records\%locale%\npc.sql >> create_tables.sql
type .\records\%locale%\npc_actions.sql >> create_tables.sql
type .\records\%locale%\npc_chats.sql >> create_tables.sql
type .\records\%locale%\pet_items.sql >> create_tables.sql
type .\records\%locale%\pet_types.sql >> create_tables.sql
type .\records\%locale%\polymorphs.sql >> create_tables.sql
type .\records\%locale%\resolvents.sql >> create_tables.sql
type .\records\%locale%\shops.sql >> create_tables.sql
type .\records\%locale%\skills.sql >> create_tables.sql
type .\records\%locale%\spawn_mobs.sql >> create_tables.sql
type .\records\%locale%\spawn_boss.sql >> create_tables.sql
type .\records\%locale%\spawn_doors.sql >> create_tables.sql
type .\records\%locale%\spawn_lights.sql >> create_tables.sql
type .\records\%locale%\spawn_npc.sql >> create_tables.sql
type .\records\%locale%\spawn_times.sql >> create_tables.sql
type .\records\%locale%\spawn_traps.sql >> create_tables.sql
type .\records\%locale%\spawn_ub.sql >> create_tables.sql
type .\records\%locale%\spr_actions.sql >> create_tables.sql
type .\records\%locale%\towns.sql >> create_tables.sql
type .\records\%locale%\traps.sql >> create_tables.sql
type .\records\%locale%\ub_managers.sql >> create_tables.sql
type .\records\%locale%\ub_settings.sql >> create_tables.sql
type .\records\%locale%\ub_times.sql >> create_tables.sql
type .\records\%locale%\weapons.sql >> create_tables.sql
type .\records\%locale%\weapon_skills.sql >> create_tables.sql
