#!/bin/bash
cat ./taiwanese/accounts.sql > create_tables.sql
cat ./taiwanese/armor.sql >> create_tables.sql
cat ./taiwanese/armor_set.sql >> create_tables.sql
cat ./taiwanese/ban_ip.sql >> create_tables.sql
cat ./taiwanese/beginner_items.sql >> create_tables.sql
cat ./taiwanese/board.sql >> create_tables.sql
cat ./taiwanese/board_auction.sql >> create_tables.sql
cat ./taiwanese/castle.sql >> create_tables.sql
cat ./taiwanese/character_buddys.sql >> create_tables.sql
cat ./taiwanese/character_buffs.sql >> create_tables.sql
cat ./taiwanese/character_config.sql >> create_tables.sql
cat ./taiwanese/character_quests.sql >> create_tables.sql
cat ./taiwanese/character_skills.sql >> create_tables.sql
cat ./taiwanese/character_teleport.sql >> create_tables.sql
cat ./taiwanese/characters.sql >> create_tables.sql
cat ./taiwanese/clan_data.sql >> create_tables.sql
cat ./taiwanese/commands.sql >> create_tables.sql
cat ./taiwanese/cooking_ingredients.sql >> create_tables.sql
cat ./taiwanese/cooking_recipes.sql >> create_tables.sql
cat ./taiwanese/door_gfxs.sql >> create_tables.sql
cat ./taiwanese/drop_item.sql >> create_tables.sql
cat ./taiwanese/droplist.sql >> create_tables.sql
cat ./taiwanese/dungeon.sql >> create_tables.sql
cat ./taiwanese/dungeon_random.sql >> create_tables.sql
cat ./taiwanese/etcitem.sql >> create_tables.sql
cat ./taiwanese/getback.sql >> create_tables.sql
cat ./taiwanese/getback_restart.sql >> create_tables.sql
cat ./taiwanese/house.sql >> create_tables.sql
cat ./taiwanese/inn.sql >> create_tables.sql
cat ./taiwanese/inn_key.sql >> create_tables.sql
cat ./taiwanese/inventory_items.sql >> create_tables.sql
cat ./taiwanese/letter.sql >> create_tables.sql
cat ./taiwanese/log_accelerator.sql >> create_tables.sql
cat ./taiwanese/log_chat.sql >> create_tables.sql
cat ./taiwanese/log_enchant.sql >> create_tables.sql
cat ./taiwanese/magic_doll.sql >> create_tables.sql
cat ./taiwanese/mail.sql >> create_tables.sql
cat ./taiwanese/mapids.sql >> create_tables.sql
cat ./taiwanese/map_timer.sql >> create_tables.sql
cat ./taiwanese/mobgroup.sql >> create_tables.sql
cat ./taiwanese/mobskill.sql >> create_tables.sql
cat ./taiwanese/npc.sql >> create_tables.sql
cat ./taiwanese/npcaction.sql >> create_tables.sql
cat ./taiwanese/npcchat.sql >> create_tables.sql
cat ./taiwanese/petitem.sql >> create_tables.sql
cat ./taiwanese/pets.sql >> create_tables.sql
cat ./taiwanese/pettypes.sql >> create_tables.sql
cat ./taiwanese/polymorphs.sql >> create_tables.sql
cat ./taiwanese/race_ticket.sql >> create_tables.sql
cat ./taiwanese/resolvent.sql >> create_tables.sql
cat ./taiwanese/shop.sql >> create_tables.sql
cat ./taiwanese/skills.sql >> create_tables.sql
cat ./taiwanese/spawnlist.sql >> create_tables.sql
cat ./taiwanese/spawnlist_boss.sql >> create_tables.sql
cat ./taiwanese/spawnlist_door.sql >> create_tables.sql
cat ./taiwanese/spawnlist_furniture.sql >> create_tables.sql
cat ./taiwanese/spawnlist_light.sql >> create_tables.sql
cat ./taiwanese/spawnlist_npc.sql >> create_tables.sql
cat ./taiwanese/spawnlist_time.sql >> create_tables.sql
cat ./taiwanese/spawnlist_trap.sql >> create_tables.sql
cat ./taiwanese/spawnlist_ub.sql >> create_tables.sql
cat ./taiwanese/spr_action.sql >> create_tables.sql
cat ./taiwanese/town.sql >> create_tables.sql
cat ./taiwanese/trap.sql >> create_tables.sql
cat ./taiwanese/ub_managers.sql >> create_tables.sql
cat ./taiwanese/ub_settings.sql >> create_tables.sql
cat ./taiwanese/ub_times.sql >> create_tables.sql
cat ./taiwanese/weapon.sql >> create_tables.sql
cat ./taiwanese/weapon_skill.sql >> create_tables.sql
